// Code generated by fbs2struct. DO NOT EDIT.
package fbtbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
	fb "github.com/vvisun/kkdg/proto/pbbase/fbbase"
)

// Int32 对应 table Int32，用于 flatbuffer 编解码
type Int32 struct {
	Value int32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int32) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fb.Int32Start(builder)
	fb.Int32AddValue(builder, s.Value)
	return fb.Int32End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int32) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsInt32(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int32) unpackFrom(t *fb.Int32) {
	s.Value = t.Value()
}

// Uint32 对应 table Uint32，用于 flatbuffer 编解码
type Uint32 struct {
	Value uint32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Uint32) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fb.Uint32Start(builder)
	fb.Uint32AddValue(builder, s.Value)
	return fb.Uint32End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Uint32) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsUint32(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Uint32) unpackFrom(t *fb.Uint32) {
	s.Value = t.Value()
}

// Int64 对应 table Int64，用于 flatbuffer 编解码
type Int64 struct {
	Value int64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int64) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fb.Int64Start(builder)
	fb.Int64AddValue(builder, s.Value)
	return fb.Int64End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int64) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsInt64(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int64) unpackFrom(t *fb.Int64) {
	s.Value = t.Value()
}

// UInt64 对应 table UInt64，用于 flatbuffer 编解码
type UInt64 struct {
	Value uint64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *UInt64) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fb.UInt64Start(builder)
	fb.UInt64AddValue(builder, s.Value)
	return fb.UInt64End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *UInt64) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsUInt64(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *UInt64) unpackFrom(t *fb.UInt64) {
	s.Value = t.Value()
}

// Bool 对应 table Bool，用于 flatbuffer 编解码
type Bool struct {
	Value bool
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Bool) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fb.BoolStart(builder)
	fb.BoolAddValue(builder, s.Value)
	return fb.BoolEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Bool) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsBool(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Bool) unpackFrom(t *fb.Bool) {
	s.Value = t.Value()
}

// String 对应 table String，用于 flatbuffer 编解码
type String struct {
	Value string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *String) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oValue flatbuffers.UOffsetT
	if s.Value != "" { oValue = builder.CreateString(s.Value) }
	fb.StringStart(builder)
	fb.StringAddValue(builder, oValue)
	return fb.StringEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *String) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsString(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *String) unpackFrom(t *fb.String) {
	s.Value = string(t.Value())
}

// Bytes 对应 table Bytes，用于 flatbuffer 编解码
type Bytes struct {
	Value []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Bytes) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var pValue flatbuffers.UOffsetT
	if len(s.Value) > 0 {
		fb.BytesStartValueVector(builder, len(s.Value))
		for i := len(s.Value) - 1; i >= 0; i-- { builder.PrependByte(s.Value[i]) }
		pValue = builder.EndVector(len(s.Value))
	}
	fb.BytesStart(builder)
	fb.BytesAddValue(builder, pValue)
	return fb.BytesEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Bytes) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsBytes(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Bytes) unpackFrom(t *fb.Bytes) {
	s.Value = t.ValueBytes()
}

// BytesList 对应 table BytesList，用于 flatbuffer 编解码
type BytesList struct {
	ValueList []*Bytes
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *BytesList) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fb.BytesListStart(builder)
	// TODO: Bytes ValueList
	return fb.BytesListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *BytesList) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsBytesList(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *BytesList) unpackFrom(t *fb.BytesList) {
	// TODO: vector Bytes
}

// Int64List 对应 table Int64List，用于 flatbuffer 编解码
type Int64List struct {
	ValueList []int64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int64List) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		fb.Int64ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependInt64(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	fb.Int64ListStart(builder)
	fb.Int64ListAddValueList(builder, pValueList)
	return fb.Int64ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int64List) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsInt64List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int64List) unpackFrom(t *fb.Int64List) {
	n := t.ValueListLength()
	s.ValueList = make([]int64, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// UInt64List 对应 table UInt64List，用于 flatbuffer 编解码
type UInt64List struct {
	ValueList []uint64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *UInt64List) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		fb.UInt64ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependUint64(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	fb.UInt64ListStart(builder)
	fb.UInt64ListAddValueList(builder, pValueList)
	return fb.UInt64ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *UInt64List) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsUInt64List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *UInt64List) unpackFrom(t *fb.UInt64List) {
	n := t.ValueListLength()
	s.ValueList = make([]uint64, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// Int32List 对应 table Int32List，用于 flatbuffer 编解码
type Int32List struct {
	ValueList []int32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int32List) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		fb.Int32ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependInt32(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	fb.Int32ListStart(builder)
	fb.Int32ListAddValueList(builder, pValueList)
	return fb.Int32ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int32List) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsInt32List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int32List) unpackFrom(t *fb.Int32List) {
	n := t.ValueListLength()
	s.ValueList = make([]int32, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// Uint32List 对应 table Uint32List，用于 flatbuffer 编解码
type Uint32List struct {
	ValueList []uint32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Uint32List) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		fb.Uint32ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependUint32(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	fb.Uint32ListStart(builder)
	fb.Uint32ListAddValueList(builder, pValueList)
	return fb.Uint32ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Uint32List) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsUint32List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Uint32List) unpackFrom(t *fb.Uint32List) {
	n := t.ValueListLength()
	s.ValueList = make([]uint32, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// StringList 对应 table StringList，用于 flatbuffer 编解码
type StringList struct {
	ValueList []string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *StringList) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		offs := make([]flatbuffers.UOffsetT, len(s.ValueList))
		for i, v := range s.ValueList { offs[i] = builder.CreateString(v) }
		fb.StringListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependUOffsetT(offs[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	fb.StringListStart(builder)
	fb.StringListAddValueList(builder, pValueList)
	return fb.StringListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *StringList) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsStringList(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *StringList) unpackFrom(t *fb.StringList) {
	n := t.ValueListLength()
	s.ValueList = make([]string, n)
	for i := 0; i < n; i++ { s.ValueList[i] = string(t.ValueList(i)) }
}

