namespace fbcluster;

table MemberInfo {
  NodeID: string;
  NodeType: string;
  Address: string;
  RpcAddress: string;
  Weight: long;
  Status: long;
}

table MemberInfoList {
  List: [MemberInfo];
}

table DiscoveryRequest {
  RequesterID: string;
}

table ClusterPacket {
  BuildTime: long;
  Timeout: long;
  SourcePath: string;
  TargetPath: string;
  Sid: string;
  FuncName: string;
  ArgBytes: [ubyte];
}

table ClusterRequest {
  RequestID: string;
  SourceNodeID: string;
  Packet: ClusterPacket;
}

table ClusterResponse {
  RequestID: string;
  Code: int;
  Data: [ubyte];
}

