// Code generated by fbs2struct. DO NOT EDIT.
package fbtgate

import (
	flatbuffers "github.com/google/flatbuffers/go"
	fb "github.com/vvisun/kkdg/proto/ptoflats/pbgate/fbgate"
)

// RpcMsgRegister 对应 table RpcMsgRegister，用于 flatbuffer 编解码
type RpcMsgRegister struct {
	ShardIdx int32
	NodeId string
	NodeType string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcMsgRegister) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oNodeId flatbuffers.UOffsetT
	if s.NodeId != "" { oNodeId = builder.CreateString(s.NodeId) }
	var oNodeType flatbuffers.UOffsetT
	if s.NodeType != "" { oNodeType = builder.CreateString(s.NodeType) }
	fb.RpcMsgRegisterStart(builder)
	fb.RpcMsgRegisterAddShardIdx(builder, s.ShardIdx)
	fb.RpcMsgRegisterAddNodeId(builder, oNodeId)
	fb.RpcMsgRegisterAddNodeType(builder, oNodeType)
	return fb.RpcMsgRegisterEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcMsgRegister) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcMsgRegister(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcMsgRegister) unpackFrom(t *fb.RpcMsgRegister) {
	s.ShardIdx = t.ShardIdx()
	s.NodeId = string(t.NodeId())
	s.NodeType = string(t.NodeType())
}

// RpcS2Client 对应 table RpcS2Client，用于 flatbuffer 编解码
type RpcS2Client struct {
	ClientId string
	Payload []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcS2Client) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oClientId flatbuffers.UOffsetT
	if s.ClientId != "" { oClientId = builder.CreateString(s.ClientId) }
	var pPayload flatbuffers.UOffsetT
	if len(s.Payload) > 0 {
		fb.RpcS2ClientStartPayloadVector(builder, len(s.Payload))
		for i := len(s.Payload) - 1; i >= 0; i-- { builder.PrependByte(s.Payload[i]) }
		pPayload = builder.EndVector(len(s.Payload))
	}
	fb.RpcS2ClientStart(builder)
	fb.RpcS2ClientAddClientId(builder, oClientId)
	fb.RpcS2ClientAddPayload(builder, pPayload)
	return fb.RpcS2ClientEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcS2Client) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcS2Client(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcS2Client) unpackFrom(t *fb.RpcS2Client) {
	s.ClientId = string(t.ClientId())
	s.Payload = t.PayloadBytes()
}

// RpcS2Clients 对应 table RpcS2Clients，用于 flatbuffer 编解码
type RpcS2Clients struct {
	ClientIds []string
	Payload []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcS2Clients) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pClientIds := flatbuffers.UOffsetT(0)
	if len(s.ClientIds) > 0 {
		offs := make([]flatbuffers.UOffsetT, len(s.ClientIds))
		for i, v := range s.ClientIds { offs[i] = builder.CreateString(v) }
		fb.RpcS2ClientsStartClientIdsVector(builder, len(s.ClientIds))
		for i := len(s.ClientIds) - 1; i >= 0; i-- { builder.PrependUOffsetT(offs[i]) }
		pClientIds = builder.EndVector(len(s.ClientIds))
	}
	var pPayload flatbuffers.UOffsetT
	if len(s.Payload) > 0 {
		fb.RpcS2ClientsStartPayloadVector(builder, len(s.Payload))
		for i := len(s.Payload) - 1; i >= 0; i-- { builder.PrependByte(s.Payload[i]) }
		pPayload = builder.EndVector(len(s.Payload))
	}
	fb.RpcS2ClientsStart(builder)
	fb.RpcS2ClientsAddClientIds(builder, pClientIds)
	fb.RpcS2ClientsAddPayload(builder, pPayload)
	return fb.RpcS2ClientsEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcS2Clients) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcS2Clients(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcS2Clients) unpackFrom(t *fb.RpcS2Clients) {
	n := t.ClientIdsLength()
	s.ClientIds = make([]string, n)
	for i := 0; i < n; i++ { s.ClientIds[i] = string(t.ClientIds(i)) }
	s.Payload = t.PayloadBytes()
}

// RpcC2S 对应 table RpcC2S，用于 flatbuffer 编解码
type RpcC2S struct {
	ClientId string
	GateNodeId string
	Payload []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcC2S) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oClientId flatbuffers.UOffsetT
	if s.ClientId != "" { oClientId = builder.CreateString(s.ClientId) }
	var oGateNodeId flatbuffers.UOffsetT
	if s.GateNodeId != "" { oGateNodeId = builder.CreateString(s.GateNodeId) }
	var pPayload flatbuffers.UOffsetT
	if len(s.Payload) > 0 {
		fb.RpcC2SStartPayloadVector(builder, len(s.Payload))
		for i := len(s.Payload) - 1; i >= 0; i-- { builder.PrependByte(s.Payload[i]) }
		pPayload = builder.EndVector(len(s.Payload))
	}
	fb.RpcC2SStart(builder)
	fb.RpcC2SAddClientId(builder, oClientId)
	fb.RpcC2SAddGateNodeId(builder, oGateNodeId)
	fb.RpcC2SAddPayload(builder, pPayload)
	return fb.RpcC2SEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcC2S) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcC2S(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcC2S) unpackFrom(t *fb.RpcC2S) {
	s.ClientId = string(t.ClientId())
	s.GateNodeId = string(t.GateNodeId())
	s.Payload = t.PayloadBytes()
}

// RpcClientDisconnect 对应 table RpcClientDisconnect，用于 flatbuffer 编解码
type RpcClientDisconnect struct {
	ClientId string
	ClientIds []string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcClientDisconnect) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oClientId flatbuffers.UOffsetT
	if s.ClientId != "" { oClientId = builder.CreateString(s.ClientId) }
	pClientIds := flatbuffers.UOffsetT(0)
	if len(s.ClientIds) > 0 {
		offs := make([]flatbuffers.UOffsetT, len(s.ClientIds))
		for i, v := range s.ClientIds { offs[i] = builder.CreateString(v) }
		fb.RpcClientDisconnectStartClientIdsVector(builder, len(s.ClientIds))
		for i := len(s.ClientIds) - 1; i >= 0; i-- { builder.PrependUOffsetT(offs[i]) }
		pClientIds = builder.EndVector(len(s.ClientIds))
	}
	fb.RpcClientDisconnectStart(builder)
	fb.RpcClientDisconnectAddClientId(builder, oClientId)
	fb.RpcClientDisconnectAddClientIds(builder, pClientIds)
	return fb.RpcClientDisconnectEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcClientDisconnect) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcClientDisconnect(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcClientDisconnect) unpackFrom(t *fb.RpcClientDisconnect) {
	s.ClientId = string(t.ClientId())
	n := t.ClientIdsLength()
	s.ClientIds = make([]string, n)
	for i := 0; i < n; i++ { s.ClientIds[i] = string(t.ClientIds(i)) }
}

// RpcAllocClient 对应 table RpcAllocClient，用于 flatbuffer 编解码
type RpcAllocClient struct {
	ClientId string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcAllocClient) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oClientId flatbuffers.UOffsetT
	if s.ClientId != "" { oClientId = builder.CreateString(s.ClientId) }
	fb.RpcAllocClientStart(builder)
	fb.RpcAllocClientAddClientId(builder, oClientId)
	return fb.RpcAllocClientEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcAllocClient) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcAllocClient(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcAllocClient) unpackFrom(t *fb.RpcAllocClient) {
	s.ClientId = string(t.ClientId())
}

// RpcClientLoginLogout 对应 table RpcClientLoginLogout，用于 flatbuffer 编解码
type RpcClientLoginLogout struct {
	UserId int64
	IsLogin bool
	ClientId string
	NodeType string
	NodeId string
	GateNodeId string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcClientLoginLogout) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oClientId flatbuffers.UOffsetT
	if s.ClientId != "" { oClientId = builder.CreateString(s.ClientId) }
	var oNodeType flatbuffers.UOffsetT
	if s.NodeType != "" { oNodeType = builder.CreateString(s.NodeType) }
	var oNodeId flatbuffers.UOffsetT
	if s.NodeId != "" { oNodeId = builder.CreateString(s.NodeId) }
	var oGateNodeId flatbuffers.UOffsetT
	if s.GateNodeId != "" { oGateNodeId = builder.CreateString(s.GateNodeId) }
	fb.RpcClientLoginLogoutStart(builder)
	fb.RpcClientLoginLogoutAddUserId(builder, s.UserId)
	fb.RpcClientLoginLogoutAddIsLogin(builder, s.IsLogin)
	fb.RpcClientLoginLogoutAddClientId(builder, oClientId)
	fb.RpcClientLoginLogoutAddNodeType(builder, oNodeType)
	fb.RpcClientLoginLogoutAddNodeId(builder, oNodeId)
	fb.RpcClientLoginLogoutAddGateNodeId(builder, oGateNodeId)
	return fb.RpcClientLoginLogoutEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcClientLoginLogout) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcClientLoginLogout(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcClientLoginLogout) unpackFrom(t *fb.RpcClientLoginLogout) {
	s.UserId = t.UserId()
	s.IsLogin = t.IsLogin()
	s.ClientId = string(t.ClientId())
	s.NodeType = string(t.NodeType())
	s.NodeId = string(t.NodeId())
	s.GateNodeId = string(t.GateNodeId())
}

// RpcUnregister 对应 table RpcUnregister，用于 flatbuffer 编解码
type RpcUnregister struct {
	NodeId string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RpcUnregister) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oNodeId flatbuffers.UOffsetT
	if s.NodeId != "" { oNodeId = builder.CreateString(s.NodeId) }
	fb.RpcUnregisterStart(builder)
	fb.RpcUnregisterAddNodeId(builder, oNodeId)
	return fb.RpcUnregisterEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RpcUnregister) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsRpcUnregister(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RpcUnregister) unpackFrom(t *fb.RpcUnregister) {
	s.NodeId = string(t.NodeId())
}

