// Code generated by fbs2struct. DO NOT EDIT.
package fbcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// MapSettingsEntryStruct 对应 table MapSettingsEntry，用于 flatbuffer 编解码
type MapSettingsEntryStruct struct {
	Key string
	Value string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MapSettingsEntryStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oKey flatbuffers.UOffsetT
	if s.Key != "" { oKey = builder.CreateString(s.Key) }
	var oValue flatbuffers.UOffsetT
	if s.Value != "" { oValue = builder.CreateString(s.Value) }
	MapSettingsEntryStart(builder)
	MapSettingsEntryAddKey(builder, oKey)
	MapSettingsEntryAddValue(builder, oValue)
	return MapSettingsEntryEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MapSettingsEntryStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsMapSettingsEntry(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MapSettingsEntryStruct) unpackFrom(t *MapSettingsEntry) {
	s.Key = string(t.Key())
	s.Value = string(t.Value())
}

// MapExtendDataEntryStruct 对应 table MapExtendDataEntry，用于 flatbuffer 编解码
type MapExtendDataEntryStruct struct {
	Key string
	Value string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MapExtendDataEntryStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oKey flatbuffers.UOffsetT
	if s.Key != "" { oKey = builder.CreateString(s.Key) }
	var oValue flatbuffers.UOffsetT
	if s.Value != "" { oValue = builder.CreateString(s.Value) }
	MapExtendDataEntryStart(builder)
	MapExtendDataEntryAddKey(builder, oKey)
	MapExtendDataEntryAddValue(builder, oValue)
	return MapExtendDataEntryEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MapExtendDataEntryStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsMapExtendDataEntry(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MapExtendDataEntryStruct) unpackFrom(t *MapExtendDataEntry) {
	s.Key = string(t.Key())
	s.Value = string(t.Value())
}

// MemberStruct 对应 table Member，用于 flatbuffer 编解码
type MemberStruct struct {
	NodeID string
	NodeType string
	Address string
	Settings []*MapSettingsEntryStruct
	LastAt int64
	HeartbeatTimeout int64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MemberStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oNodeID flatbuffers.UOffsetT
	if s.NodeID != "" { oNodeID = builder.CreateString(s.NodeID) }
	var oNodeType flatbuffers.UOffsetT
	if s.NodeType != "" { oNodeType = builder.CreateString(s.NodeType) }
	var oAddress flatbuffers.UOffsetT
	if s.Address != "" { oAddress = builder.CreateString(s.Address) }
	MemberStart(builder)
	MemberAddNodeID(builder, oNodeID)
	MemberAddNodeType(builder, oNodeType)
	MemberAddAddress(builder, oAddress)
	// TODO: MapSettingsEntry Settings
	MemberAddLastAt(builder, s.LastAt)
	MemberAddHeartbeatTimeout(builder, s.HeartbeatTimeout)
	return MemberEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MemberStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsMember(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MemberStruct) unpackFrom(t *Member) {
	s.NodeID = string(t.NodeID())
	s.NodeType = string(t.NodeType())
	s.Address = string(t.Address())
	// TODO: vector MapSettingsEntry
	s.LastAt = t.LastAt()
	s.HeartbeatTimeout = t.HeartbeatTimeout()
}

// MemberListStruct 对应 table MemberList，用于 flatbuffer 编解码
type MemberListStruct struct {
	List []*MemberStruct
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MemberListStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	MemberListStart(builder)
	// TODO: Member List
	return MemberListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MemberListStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsMemberList(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MemberListStruct) unpackFrom(t *MemberList) {
	// TODO: vector Member
}

// DiscoveryRequestStruct 对应 table DiscoveryRequest，用于 flatbuffer 编解码
type DiscoveryRequestStruct struct {
	RequesterID string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *DiscoveryRequestStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequesterID flatbuffers.UOffsetT
	if s.RequesterID != "" { oRequesterID = builder.CreateString(s.RequesterID) }
	DiscoveryRequestStart(builder)
	DiscoveryRequestAddRequesterID(builder, oRequesterID)
	return DiscoveryRequestEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *DiscoveryRequestStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsDiscoveryRequest(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *DiscoveryRequestStruct) unpackFrom(t *DiscoveryRequest) {
	s.RequesterID = string(t.RequesterID())
}

// ClusterPacketStruct 对应 table ClusterPacket，用于 flatbuffer 编解码
type ClusterPacketStruct struct {
	BuildTime int64
	Timeout int64
	SourcePath string
	TargetPath string
	FuncName string
	ArgBytes []byte
	Sid string
	Uid int64
	AgentPath string
	Ip string
	ExtendData []*MapExtendDataEntryStruct
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterPacketStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oSourcePath flatbuffers.UOffsetT
	if s.SourcePath != "" { oSourcePath = builder.CreateString(s.SourcePath) }
	var oTargetPath flatbuffers.UOffsetT
	if s.TargetPath != "" { oTargetPath = builder.CreateString(s.TargetPath) }
	var oFuncName flatbuffers.UOffsetT
	if s.FuncName != "" { oFuncName = builder.CreateString(s.FuncName) }
	var pArgBytes flatbuffers.UOffsetT
	if len(s.ArgBytes) > 0 {
		ClusterPacketStartArgBytesVector(builder, len(s.ArgBytes))
		for i := len(s.ArgBytes) - 1; i >= 0; i-- { builder.PrependByte(s.ArgBytes[i]) }
		pArgBytes = builder.EndVector(len(s.ArgBytes))
	}
	var oSid flatbuffers.UOffsetT
	if s.Sid != "" { oSid = builder.CreateString(s.Sid) }
	var oAgentPath flatbuffers.UOffsetT
	if s.AgentPath != "" { oAgentPath = builder.CreateString(s.AgentPath) }
	var oIp flatbuffers.UOffsetT
	if s.Ip != "" { oIp = builder.CreateString(s.Ip) }
	ClusterPacketStart(builder)
	ClusterPacketAddBuildTime(builder, s.BuildTime)
	ClusterPacketAddTimeout(builder, s.Timeout)
	ClusterPacketAddSourcePath(builder, oSourcePath)
	ClusterPacketAddTargetPath(builder, oTargetPath)
	ClusterPacketAddFuncName(builder, oFuncName)
	ClusterPacketAddArgBytes(builder, pArgBytes)
	ClusterPacketAddSid(builder, oSid)
	ClusterPacketAddUid(builder, s.Uid)
	ClusterPacketAddAgentPath(builder, oAgentPath)
	ClusterPacketAddIp(builder, oIp)
	// TODO: MapExtendDataEntry ExtendData
	return ClusterPacketEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterPacketStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsClusterPacket(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterPacketStruct) unpackFrom(t *ClusterPacket) {
	s.BuildTime = t.BuildTime()
	s.Timeout = t.Timeout()
	s.SourcePath = string(t.SourcePath())
	s.TargetPath = string(t.TargetPath())
	s.FuncName = string(t.FuncName())
	s.ArgBytes = t.ArgBytesBytes()
	s.Sid = string(t.Sid())
	s.Uid = t.Uid()
	s.AgentPath = string(t.AgentPath())
	s.Ip = string(t.Ip())
	// TODO: vector MapExtendDataEntry
}

// ClusterRequestStruct 对应 table ClusterRequest，用于 flatbuffer 编解码
type ClusterRequestStruct struct {
	RequestID string
	SourceNodeID string
	Packet *ClusterPacketStruct
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterRequestStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequestID flatbuffers.UOffsetT
	if s.RequestID != "" { oRequestID = builder.CreateString(s.RequestID) }
	var oSourceNodeID flatbuffers.UOffsetT
	if s.SourceNodeID != "" { oSourceNodeID = builder.CreateString(s.SourceNodeID) }
	ClusterRequestStart(builder)
	ClusterRequestAddRequestID(builder, oRequestID)
	ClusterRequestAddSourceNodeID(builder, oSourceNodeID)
	// TODO: ClusterPacket Packet
	return ClusterRequestEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterRequestStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsClusterRequest(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterRequestStruct) unpackFrom(t *ClusterRequest) {
	s.RequestID = string(t.RequestID())
	s.SourceNodeID = string(t.SourceNodeID())
	// TODO: ClusterPacket
}

// ClusterResponseStruct 对应 table ClusterResponse，用于 flatbuffer 编解码
type ClusterResponseStruct struct {
	RequestID string
	Code int32
	Data []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterResponseStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequestID flatbuffers.UOffsetT
	if s.RequestID != "" { oRequestID = builder.CreateString(s.RequestID) }
	var pData flatbuffers.UOffsetT
	if len(s.Data) > 0 {
		ClusterResponseStartDataVector(builder, len(s.Data))
		for i := len(s.Data) - 1; i >= 0; i-- { builder.PrependByte(s.Data[i]) }
		pData = builder.EndVector(len(s.Data))
	}
	ClusterResponseStart(builder)
	ClusterResponseAddRequestID(builder, oRequestID)
	ClusterResponseAddCode(builder, s.Code)
	ClusterResponseAddData(builder, pData)
	return ClusterResponseEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterResponseStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsClusterResponse(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterResponseStruct) unpackFrom(t *ClusterResponse) {
	s.RequestID = string(t.RequestID())
	s.Code = t.Code()
	s.Data = t.DataBytes()
}

