// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClusterPacket struct {
	_tab flatbuffers.Table
}

func GetRootAsClusterPacket(buf []byte, offset flatbuffers.UOffsetT) *ClusterPacket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClusterPacket{}
	x.Init(buf, n+offset)
	return x
}

func FinishClusterPacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClusterPacket(buf []byte, offset flatbuffers.UOffsetT) *ClusterPacket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClusterPacket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClusterPacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClusterPacket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClusterPacket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClusterPacket) BuildTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClusterPacket) MutateBuildTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *ClusterPacket) Timeout() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClusterPacket) MutateTimeout(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *ClusterPacket) SourcePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterPacket) TargetPath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterPacket) Sid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterPacket) FuncName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterPacket) ArgBytes(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ClusterPacket) ArgBytesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ClusterPacket) ArgBytesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterPacket) MutateArgBytes(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ClusterPacketStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ClusterPacketAddBuildTime(builder *flatbuffers.Builder, buildTime int64) {
	builder.PrependInt64Slot(0, buildTime, 0)
}
func ClusterPacketAddTimeout(builder *flatbuffers.Builder, timeout int64) {
	builder.PrependInt64Slot(1, timeout, 0)
}
func ClusterPacketAddSourcePath(builder *flatbuffers.Builder, sourcePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sourcePath), 0)
}
func ClusterPacketAddTargetPath(builder *flatbuffers.Builder, targetPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(targetPath), 0)
}
func ClusterPacketAddSid(builder *flatbuffers.Builder, sid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(sid), 0)
}
func ClusterPacketAddFuncName(builder *flatbuffers.Builder, funcName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(funcName), 0)
}
func ClusterPacketAddArgBytes(builder *flatbuffers.Builder, argBytes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(argBytes), 0)
}
func ClusterPacketStartArgBytesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ClusterPacketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
