// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MapExtendDataEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMapExtendDataEntry(buf []byte, offset flatbuffers.UOffsetT) *MapExtendDataEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MapExtendDataEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMapExtendDataEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMapExtendDataEntry(buf []byte, offset flatbuffers.UOffsetT) *MapExtendDataEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MapExtendDataEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMapExtendDataEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MapExtendDataEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MapExtendDataEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MapExtendDataEntry) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MapExtendDataEntry) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MapExtendDataEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MapExtendDataEntryAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func MapExtendDataEntryAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func MapExtendDataEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
