// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MemberList struct {
	_tab flatbuffers.Table
}

func GetRootAsMemberList(buf []byte, offset flatbuffers.UOffsetT) *MemberList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MemberList{}
	x.Init(buf, n+offset)
	return x
}

func FinishMemberListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMemberList(buf []byte, offset flatbuffers.UOffsetT) *MemberList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MemberList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMemberListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MemberList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MemberList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MemberList) List(obj *Member, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MemberList) ListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MemberListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MemberListAddList(builder *flatbuffers.Builder, list flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(list), 0)
}
func MemberListStartListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MemberListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
