// Code generated by fbs2struct. DO NOT EDIT.
package fbrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// FrameStruct 对应 table Frame，用于 flatbuffer 编解码
type FrameStruct struct {
	T uint32
	ID uint64
	DL int64
	M string
	P []byte
	Code int32
	Err string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *FrameStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oM flatbuffers.UOffsetT
	if s.M != "" { oM = builder.CreateString(s.M) }
	var pP flatbuffers.UOffsetT
	if len(s.P) > 0 {
		FrameStartPVector(builder, len(s.P))
		for i := len(s.P) - 1; i >= 0; i-- { builder.PrependByte(s.P[i]) }
		pP = builder.EndVector(len(s.P))
	}
	var oErr flatbuffers.UOffsetT
	if s.Err != "" { oErr = builder.CreateString(s.Err) }
	FrameStart(builder)
	FrameAddT(builder, s.T)
	FrameAddId(builder, s.ID)
	FrameAddDl(builder, s.DL)
	FrameAddM(builder, oM)
	FrameAddP(builder, pP)
	FrameAddCode(builder, s.Code)
	FrameAddErr(builder, oErr)
	return FrameEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *FrameStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsFrame(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *FrameStruct) unpackFrom(t *Frame) {
	s.T = t.T()
	s.ID = t.Id()
	s.DL = t.Dl()
	s.M = string(t.M())
	s.P = t.PBytes()
	s.Code = t.Code()
	s.Err = string(t.Err())
}

// TransMsgStruct 对应 table TransMsg，用于 flatbuffer 编解码
type TransMsgStruct struct {
	ClientId uint64
	Data []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *TransMsgStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var pData flatbuffers.UOffsetT
	if len(s.Data) > 0 {
		TransMsgStartDataVector(builder, len(s.Data))
		for i := len(s.Data) - 1; i >= 0; i-- { builder.PrependByte(s.Data[i]) }
		pData = builder.EndVector(len(s.Data))
	}
	TransMsgStart(builder)
	TransMsgAddClientId(builder, s.ClientId)
	TransMsgAddData(builder, pData)
	return TransMsgEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *TransMsgStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsTransMsg(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *TransMsgStruct) unpackFrom(t *TransMsg) {
	s.ClientId = t.ClientId()
	s.Data = t.DataBytes()
}

// TransBroadMsgStruct 对应 table TransBroadMsg，用于 flatbuffer 编解码
type TransBroadMsgStruct struct {
	ClientIdList []uint64
	Data []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *TransBroadMsgStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pClientIdList := flatbuffers.UOffsetT(0)
	if len(s.ClientIdList) > 0 {
		TransBroadMsgStartClientIdListVector(builder, len(s.ClientIdList))
		for i := len(s.ClientIdList) - 1; i >= 0; i-- { builder.PrependUint64(s.ClientIdList[i]) }
		pClientIdList = builder.EndVector(len(s.ClientIdList))
	}
	var pData flatbuffers.UOffsetT
	if len(s.Data) > 0 {
		TransBroadMsgStartDataVector(builder, len(s.Data))
		for i := len(s.Data) - 1; i >= 0; i-- { builder.PrependByte(s.Data[i]) }
		pData = builder.EndVector(len(s.Data))
	}
	TransBroadMsgStart(builder)
	TransBroadMsgAddClientIdList(builder, pClientIdList)
	TransBroadMsgAddData(builder, pData)
	return TransBroadMsgEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *TransBroadMsgStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsTransBroadMsg(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *TransBroadMsgStruct) unpackFrom(t *TransBroadMsg) {
	n := t.ClientIdListLength()
		s.ClientIdList = make([]uint64, n)
		for i := 0; i < n; i++ { s.ClientIdList[i] = t.ClientIdList(i) }
	s.Data = t.DataBytes()
}

