// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsTransMsg(buf []byte, offset flatbuffers.UOffsetT) *TransMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransMsg(buf []byte, offset flatbuffers.UOffsetT) *TransMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransMsg) ClientId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TransMsg) MutateClientId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *TransMsg) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TransMsg) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TransMsg) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransMsg) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func TransMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TransMsgAddClientId(builder *flatbuffers.Builder, clientId uint64) {
	builder.PrependUint64Slot(0, clientId, 0)
}
func TransMsgAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func TransMsgStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TransMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
