// Code generated by fbs2struct. DO NOT EDIT.
package fbtcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
	fb "github.com/vvisun/kkdg/proto/ptoflats/pbcluster/fbcluster"
)

// MapSettingsEntry 对应 table MapSettingsEntry，用于 flatbuffer 编解码
type MapSettingsEntry struct {
	Key string
	Value string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MapSettingsEntry) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oKey flatbuffers.UOffsetT
	if s.Key != "" { oKey = builder.CreateString(s.Key) }
	var oValue flatbuffers.UOffsetT
	if s.Value != "" { oValue = builder.CreateString(s.Value) }
	fb.MapSettingsEntryStart(builder)
	fb.MapSettingsEntryAddKey(builder, oKey)
	fb.MapSettingsEntryAddValue(builder, oValue)
	return fb.MapSettingsEntryEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MapSettingsEntry) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsMapSettingsEntry(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MapSettingsEntry) unpackFrom(t *fb.MapSettingsEntry) {
	s.Key = string(t.Key())
	s.Value = string(t.Value())
}

// MemberInfo 对应 table MemberInfo，用于 flatbuffer 编解码
type MemberInfo struct {
	NodeID string
	NodeType string
	Address string
	Weight int64
	Status int64
	Settings []*MapSettingsEntry
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MemberInfo) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oNodeId flatbuffers.UOffsetT
	if s.NodeID != "" { oNodeId = builder.CreateString(s.NodeID) }
	var oNodeType flatbuffers.UOffsetT
	if s.NodeType != "" { oNodeType = builder.CreateString(s.NodeType) }
	var oAddress flatbuffers.UOffsetT
	if s.Address != "" { oAddress = builder.CreateString(s.Address) }
	pSettings := flatbuffers.UOffsetT(0)
	if len(s.Settings) > 0 {
		fb.MemberInfoStartSettingsVector(builder, len(s.Settings))
		for i := len(s.Settings) - 1; i >= 0; i-- { builder.PrependUOffsetT(s.Settings[i].Pack(builder)) }
		pSettings = builder.EndVector(len(s.Settings))
	}
	fb.MemberInfoStart(builder)
	fb.MemberInfoAddNodeId(builder, oNodeId)
	fb.MemberInfoAddNodeType(builder, oNodeType)
	fb.MemberInfoAddAddress(builder, oAddress)
	fb.MemberInfoAddWeight(builder, s.Weight)
	fb.MemberInfoAddStatus(builder, s.Status)
	fb.MemberInfoAddSettings(builder, pSettings)
	return fb.MemberInfoEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MemberInfo) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsMemberInfo(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MemberInfo) unpackFrom(t *fb.MemberInfo) {
	s.NodeID = string(t.NodeId())
	s.NodeType = string(t.NodeType())
	s.Address = string(t.Address())
	s.Weight = t.Weight()
	s.Status = t.Status()
	n := t.SettingsLength()
	s.Settings = make([]*MapSettingsEntry, n)
	var obj fb.MapSettingsEntry
	for i := 0; i < n; i++ {
		if t.Settings(&obj, i) {
			e := &MapSettingsEntry{}
			e.unpackFrom(&obj)
			s.Settings[i] = e
		}
	}
}

// MemberInfoList 对应 table MemberInfoList，用于 flatbuffer 编解码
type MemberInfoList struct {
	List []*MemberInfo
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MemberInfoList) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pList := flatbuffers.UOffsetT(0)
	if len(s.List) > 0 {
		fb.MemberInfoListStartListVector(builder, len(s.List))
		for i := len(s.List) - 1; i >= 0; i-- { builder.PrependUOffsetT(s.List[i].Pack(builder)) }
		pList = builder.EndVector(len(s.List))
	}
	fb.MemberInfoListStart(builder)
	fb.MemberInfoListAddList(builder, pList)
	return fb.MemberInfoListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MemberInfoList) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsMemberInfoList(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MemberInfoList) unpackFrom(t *fb.MemberInfoList) {
	n := t.ListLength()
	s.List = make([]*MemberInfo, n)
	var obj fb.MemberInfo
	for i := 0; i < n; i++ {
		if t.List(&obj, i) {
			e := &MemberInfo{}
			e.unpackFrom(&obj)
			s.List[i] = e
		}
	}
}

// DiscoveryRequest 对应 table DiscoveryRequest，用于 flatbuffer 编解码
type DiscoveryRequest struct {
	RequesterID string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *DiscoveryRequest) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequesterId flatbuffers.UOffsetT
	if s.RequesterID != "" { oRequesterId = builder.CreateString(s.RequesterID) }
	fb.DiscoveryRequestStart(builder)
	fb.DiscoveryRequestAddRequesterId(builder, oRequesterId)
	return fb.DiscoveryRequestEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *DiscoveryRequest) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsDiscoveryRequest(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *DiscoveryRequest) unpackFrom(t *fb.DiscoveryRequest) {
	s.RequesterID = string(t.RequesterId())
}

// ClusterPacket 对应 table ClusterPacket，用于 flatbuffer 编解码
type ClusterPacket struct {
	BuildTime int64
	Timeout int64
	SourcePath string
	TargetPath string
	Sid string
	FuncName string
	ArgBytes []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterPacket) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oSourcePath flatbuffers.UOffsetT
	if s.SourcePath != "" { oSourcePath = builder.CreateString(s.SourcePath) }
	var oTargetPath flatbuffers.UOffsetT
	if s.TargetPath != "" { oTargetPath = builder.CreateString(s.TargetPath) }
	var oSid flatbuffers.UOffsetT
	if s.Sid != "" { oSid = builder.CreateString(s.Sid) }
	var oFuncName flatbuffers.UOffsetT
	if s.FuncName != "" { oFuncName = builder.CreateString(s.FuncName) }
	var pArgBytes flatbuffers.UOffsetT
	if len(s.ArgBytes) > 0 {
		fb.ClusterPacketStartArgBytesVector(builder, len(s.ArgBytes))
		for i := len(s.ArgBytes) - 1; i >= 0; i-- { builder.PrependByte(s.ArgBytes[i]) }
		pArgBytes = builder.EndVector(len(s.ArgBytes))
	}
	fb.ClusterPacketStart(builder)
	fb.ClusterPacketAddBuildTime(builder, s.BuildTime)
	fb.ClusterPacketAddTimeout(builder, s.Timeout)
	fb.ClusterPacketAddSourcePath(builder, oSourcePath)
	fb.ClusterPacketAddTargetPath(builder, oTargetPath)
	fb.ClusterPacketAddSid(builder, oSid)
	fb.ClusterPacketAddFuncName(builder, oFuncName)
	fb.ClusterPacketAddArgBytes(builder, pArgBytes)
	return fb.ClusterPacketEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterPacket) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsClusterPacket(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterPacket) unpackFrom(t *fb.ClusterPacket) {
	s.BuildTime = t.BuildTime()
	s.Timeout = t.Timeout()
	s.SourcePath = string(t.SourcePath())
	s.TargetPath = string(t.TargetPath())
	s.Sid = string(t.Sid())
	s.FuncName = string(t.FuncName())
	s.ArgBytes = t.ArgBytesBytes()
}

// ClusterRequest 对应 table ClusterRequest，用于 flatbuffer 编解码
type ClusterRequest struct {
	RequestID string
	SourceNodeID string
	Packet *ClusterPacket
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterRequest) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequestId flatbuffers.UOffsetT
	if s.RequestID != "" { oRequestId = builder.CreateString(s.RequestID) }
	var oSourceNodeId flatbuffers.UOffsetT
	if s.SourceNodeID != "" { oSourceNodeId = builder.CreateString(s.SourceNodeID) }
	var oPacket flatbuffers.UOffsetT
	if s.Packet != nil { oPacket = s.Packet.Pack(builder) }
	fb.ClusterRequestStart(builder)
	fb.ClusterRequestAddRequestId(builder, oRequestId)
	fb.ClusterRequestAddSourceNodeId(builder, oSourceNodeId)
	fb.ClusterRequestAddPacket(builder, oPacket)
	return fb.ClusterRequestEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterRequest) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsClusterRequest(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterRequest) unpackFrom(t *fb.ClusterRequest) {
	s.RequestID = string(t.RequestId())
	s.SourceNodeID = string(t.SourceNodeId())
	if p := t.Packet(nil); p != nil {
		s.Packet = &ClusterPacket{}
		s.Packet.unpackFrom(p)
	}
}

// ClusterResponse 对应 table ClusterResponse，用于 flatbuffer 编解码
type ClusterResponse struct {
	RequestID string
	Code int32
	Data []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterResponse) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequestId flatbuffers.UOffsetT
	if s.RequestID != "" { oRequestId = builder.CreateString(s.RequestID) }
	var pData flatbuffers.UOffsetT
	if len(s.Data) > 0 {
		fb.ClusterResponseStartDataVector(builder, len(s.Data))
		for i := len(s.Data) - 1; i >= 0; i-- { builder.PrependByte(s.Data[i]) }
		pData = builder.EndVector(len(s.Data))
	}
	fb.ClusterResponseStart(builder)
	fb.ClusterResponseAddRequestId(builder, oRequestId)
	fb.ClusterResponseAddCode(builder, s.Code)
	fb.ClusterResponseAddData(builder, pData)
	return fb.ClusterResponseEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterResponse) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsClusterResponse(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterResponse) unpackFrom(t *fb.ClusterResponse) {
	s.RequestID = string(t.RequestId())
	s.Code = t.Code()
	s.Data = t.DataBytes()
}

