// Code generated by fbs2struct. DO NOT EDIT.
package fbtcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
	fb "github.com/vvisun/kkdg/proto/pbcluster/fbcluster"
)

// MapSettingsEntry 对应 table MapSettingsEntry，用于 flatbuffer 编解码
type MapSettingsEntry struct {
	Key string
	Value string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MapSettingsEntry) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oKey flatbuffers.UOffsetT
	if s.Key != "" { oKey = builder.CreateString(s.Key) }
	var oValue flatbuffers.UOffsetT
	if s.Value != "" { oValue = builder.CreateString(s.Value) }
	fb.MapSettingsEntryStart(builder)
	fb.MapSettingsEntryAddKey(builder, oKey)
	fb.MapSettingsEntryAddValue(builder, oValue)
	return fb.MapSettingsEntryEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MapSettingsEntry) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsMapSettingsEntry(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MapSettingsEntry) unpackFrom(t *fb.MapSettingsEntry) {
	s.Key = string(t.Key())
	s.Value = string(t.Value())
}

// MapExtendDataEntry 对应 table MapExtendDataEntry，用于 flatbuffer 编解码
type MapExtendDataEntry struct {
	Key string
	Value string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MapExtendDataEntry) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oKey flatbuffers.UOffsetT
	if s.Key != "" { oKey = builder.CreateString(s.Key) }
	var oValue flatbuffers.UOffsetT
	if s.Value != "" { oValue = builder.CreateString(s.Value) }
	fb.MapExtendDataEntryStart(builder)
	fb.MapExtendDataEntryAddKey(builder, oKey)
	fb.MapExtendDataEntryAddValue(builder, oValue)
	return fb.MapExtendDataEntryEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MapExtendDataEntry) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsMapExtendDataEntry(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MapExtendDataEntry) unpackFrom(t *fb.MapExtendDataEntry) {
	s.Key = string(t.Key())
	s.Value = string(t.Value())
}

// Member 对应 table Member，用于 flatbuffer 编解码
type Member struct {
	NodeID string
	NodeType string
	Address string
	Settings []*MapSettingsEntry
	LastAt int64
	HeartbeatTimeout int64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Member) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oNodeId flatbuffers.UOffsetT
	if s.NodeID != "" { oNodeId = builder.CreateString(s.NodeID) }
	var oNodeType flatbuffers.UOffsetT
	if s.NodeType != "" { oNodeType = builder.CreateString(s.NodeType) }
	var oAddress flatbuffers.UOffsetT
	if s.Address != "" { oAddress = builder.CreateString(s.Address) }
	fb.MemberStart(builder)
	fb.MemberAddNodeId(builder, oNodeId)
	fb.MemberAddNodeType(builder, oNodeType)
	fb.MemberAddAddress(builder, oAddress)
	// TODO: MapSettingsEntry Settings
	fb.MemberAddLastAt(builder, s.LastAt)
	fb.MemberAddHeartbeatTimeout(builder, s.HeartbeatTimeout)
	return fb.MemberEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Member) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsMember(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Member) unpackFrom(t *fb.Member) {
	s.NodeID = string(t.NodeId())
	s.NodeType = string(t.NodeType())
	s.Address = string(t.Address())
	// TODO: vector MapSettingsEntry
	s.LastAt = t.LastAt()
	s.HeartbeatTimeout = t.HeartbeatTimeout()
}

// MemberList 对应 table MemberList，用于 flatbuffer 编解码
type MemberList struct {
	List []*Member
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *MemberList) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fb.MemberListStart(builder)
	// TODO: Member List
	return fb.MemberListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *MemberList) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsMemberList(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *MemberList) unpackFrom(t *fb.MemberList) {
	// TODO: vector Member
}

// DiscoveryRequest 对应 table DiscoveryRequest，用于 flatbuffer 编解码
type DiscoveryRequest struct {
	RequesterID string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *DiscoveryRequest) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequesterId flatbuffers.UOffsetT
	if s.RequesterID != "" { oRequesterId = builder.CreateString(s.RequesterID) }
	fb.DiscoveryRequestStart(builder)
	fb.DiscoveryRequestAddRequesterId(builder, oRequesterId)
	return fb.DiscoveryRequestEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *DiscoveryRequest) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsDiscoveryRequest(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *DiscoveryRequest) unpackFrom(t *fb.DiscoveryRequest) {
	s.RequesterID = string(t.RequesterId())
}

// ClusterPacket 对应 table ClusterPacket，用于 flatbuffer 编解码
type ClusterPacket struct {
	BuildTime int64
	Timeout int64
	SourcePath string
	TargetPath string
	FuncName string
	ArgBytes []byte
	Sid string
	Uid int64
	AgentPath string
	Ip string
	ExtendData []*MapExtendDataEntry
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterPacket) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oSourcePath flatbuffers.UOffsetT
	if s.SourcePath != "" { oSourcePath = builder.CreateString(s.SourcePath) }
	var oTargetPath flatbuffers.UOffsetT
	if s.TargetPath != "" { oTargetPath = builder.CreateString(s.TargetPath) }
	var oFuncName flatbuffers.UOffsetT
	if s.FuncName != "" { oFuncName = builder.CreateString(s.FuncName) }
	var pArgBytes flatbuffers.UOffsetT
	if len(s.ArgBytes) > 0 {
		fb.ClusterPacketStartArgBytesVector(builder, len(s.ArgBytes))
		for i := len(s.ArgBytes) - 1; i >= 0; i-- { builder.PrependByte(s.ArgBytes[i]) }
		pArgBytes = builder.EndVector(len(s.ArgBytes))
	}
	var oSid flatbuffers.UOffsetT
	if s.Sid != "" { oSid = builder.CreateString(s.Sid) }
	var oAgentPath flatbuffers.UOffsetT
	if s.AgentPath != "" { oAgentPath = builder.CreateString(s.AgentPath) }
	var oIp flatbuffers.UOffsetT
	if s.Ip != "" { oIp = builder.CreateString(s.Ip) }
	fb.ClusterPacketStart(builder)
	fb.ClusterPacketAddBuildTime(builder, s.BuildTime)
	fb.ClusterPacketAddTimeout(builder, s.Timeout)
	fb.ClusterPacketAddSourcePath(builder, oSourcePath)
	fb.ClusterPacketAddTargetPath(builder, oTargetPath)
	fb.ClusterPacketAddFuncName(builder, oFuncName)
	fb.ClusterPacketAddArgBytes(builder, pArgBytes)
	fb.ClusterPacketAddSid(builder, oSid)
	fb.ClusterPacketAddUid(builder, s.Uid)
	fb.ClusterPacketAddAgentPath(builder, oAgentPath)
	fb.ClusterPacketAddIp(builder, oIp)
	// TODO: MapExtendDataEntry ExtendData
	return fb.ClusterPacketEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterPacket) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsClusterPacket(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterPacket) unpackFrom(t *fb.ClusterPacket) {
	s.BuildTime = t.BuildTime()
	s.Timeout = t.Timeout()
	s.SourcePath = string(t.SourcePath())
	s.TargetPath = string(t.TargetPath())
	s.FuncName = string(t.FuncName())
	s.ArgBytes = t.ArgBytesBytes()
	s.Sid = string(t.Sid())
	s.Uid = t.Uid()
	s.AgentPath = string(t.AgentPath())
	s.Ip = string(t.Ip())
	// TODO: vector MapExtendDataEntry
}

// ClusterRequest 对应 table ClusterRequest，用于 flatbuffer 编解码
type ClusterRequest struct {
	RequestID string
	SourceNodeID string
	Packet *ClusterPacket
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterRequest) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequestId flatbuffers.UOffsetT
	if s.RequestID != "" { oRequestId = builder.CreateString(s.RequestID) }
	var oSourceNodeId flatbuffers.UOffsetT
	if s.SourceNodeID != "" { oSourceNodeId = builder.CreateString(s.SourceNodeID) }
	fb.ClusterRequestStart(builder)
	fb.ClusterRequestAddRequestId(builder, oRequestId)
	fb.ClusterRequestAddSourceNodeId(builder, oSourceNodeId)
	// TODO: ClusterPacket Packet
	return fb.ClusterRequestEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterRequest) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsClusterRequest(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterRequest) unpackFrom(t *fb.ClusterRequest) {
	s.RequestID = string(t.RequestId())
	s.SourceNodeID = string(t.SourceNodeId())
	// TODO: ClusterPacket
}

// ClusterResponse 对应 table ClusterResponse，用于 flatbuffer 编解码
type ClusterResponse struct {
	RequestID string
	Code int32
	Data []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *ClusterResponse) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oRequestId flatbuffers.UOffsetT
	if s.RequestID != "" { oRequestId = builder.CreateString(s.RequestID) }
	var pData flatbuffers.UOffsetT
	if len(s.Data) > 0 {
		fb.ClusterResponseStartDataVector(builder, len(s.Data))
		for i := len(s.Data) - 1; i >= 0; i-- { builder.PrependByte(s.Data[i]) }
		pData = builder.EndVector(len(s.Data))
	}
	fb.ClusterResponseStart(builder)
	fb.ClusterResponseAddRequestId(builder, oRequestId)
	fb.ClusterResponseAddCode(builder, s.Code)
	fb.ClusterResponseAddData(builder, pData)
	return fb.ClusterResponseEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *ClusterResponse) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsClusterResponse(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *ClusterResponse) unpackFrom(t *fb.ClusterResponse) {
	s.RequestID = string(t.RequestId())
	s.Code = t.Code()
	s.Data = t.DataBytes()
}

