// Code generated by fbs2struct. DO NOT EDIT.
package fbbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// Int32Struct 对应 table Int32，用于 flatbuffer 编解码
type Int32Struct struct {
	Value int32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int32Struct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	Int32Start(builder)
	Int32AddValue(builder, s.Value)
	return Int32End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int32Struct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsInt32(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int32Struct) unpackFrom(t *Int32) {
	s.Value = t.Value()
}

// Uint32Struct 对应 table Uint32，用于 flatbuffer 编解码
type Uint32Struct struct {
	Value uint32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Uint32Struct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	Uint32Start(builder)
	Uint32AddValue(builder, s.Value)
	return Uint32End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Uint32Struct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsUint32(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Uint32Struct) unpackFrom(t *Uint32) {
	s.Value = t.Value()
}

// Int64Struct 对应 table Int64，用于 flatbuffer 编解码
type Int64Struct struct {
	Value int64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int64Struct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	Int64Start(builder)
	Int64AddValue(builder, s.Value)
	return Int64End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int64Struct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsInt64(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int64Struct) unpackFrom(t *Int64) {
	s.Value = t.Value()
}

// UInt64Struct 对应 table UInt64，用于 flatbuffer 编解码
type UInt64Struct struct {
	Value uint64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *UInt64Struct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	UInt64Start(builder)
	UInt64AddValue(builder, s.Value)
	return UInt64End(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *UInt64Struct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsUInt64(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *UInt64Struct) unpackFrom(t *UInt64) {
	s.Value = t.Value()
}

// BoolStruct 对应 table Bool，用于 flatbuffer 编解码
type BoolStruct struct {
	Value bool
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *BoolStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	BoolStart(builder)
	BoolAddValue(builder, s.Value)
	return BoolEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *BoolStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsBool(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *BoolStruct) unpackFrom(t *Bool) {
	s.Value = t.Value()
}

// StringStruct 对应 table String，用于 flatbuffer 编解码
type StringStruct struct {
	Value string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *StringStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oValue flatbuffers.UOffsetT
	if s.Value != "" { oValue = builder.CreateString(s.Value) }
	StringStart(builder)
	StringAddValue(builder, oValue)
	return StringEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *StringStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsString(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *StringStruct) unpackFrom(t *String) {
	s.Value = string(t.Value())
}

// BytesStruct 对应 table Bytes，用于 flatbuffer 编解码
type BytesStruct struct {
	Value []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *BytesStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var pValue flatbuffers.UOffsetT
	if len(s.Value) > 0 {
		BytesStartValueVector(builder, len(s.Value))
		for i := len(s.Value) - 1; i >= 0; i-- { builder.PrependByte(s.Value[i]) }
		pValue = builder.EndVector(len(s.Value))
	}
	BytesStart(builder)
	BytesAddValue(builder, pValue)
	return BytesEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *BytesStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsBytes(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *BytesStruct) unpackFrom(t *Bytes) {
	s.Value = t.ValueBytes()
}

// BytesListStruct 对应 table BytesList，用于 flatbuffer 编解码
type BytesListStruct struct {
	ValueList []*BytesStruct
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *BytesListStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	BytesListStart(builder)
	// TODO: Bytes ValueList
	return BytesListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *BytesListStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsBytesList(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *BytesListStruct) unpackFrom(t *BytesList) {
	// TODO: vector Bytes
}

// Int64ListStruct 对应 table Int64List，用于 flatbuffer 编解码
type Int64ListStruct struct {
	ValueList []int64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int64ListStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		Int64ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependInt64(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	Int64ListStart(builder)
	Int64ListAddValueList(builder, pValueList)
	return Int64ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int64ListStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsInt64List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int64ListStruct) unpackFrom(t *Int64List) {
	n := t.ValueListLength()
	s.ValueList = make([]int64, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// UInt64ListStruct 对应 table UInt64List，用于 flatbuffer 编解码
type UInt64ListStruct struct {
	ValueList []uint64
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *UInt64ListStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		UInt64ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependUint64(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	UInt64ListStart(builder)
	UInt64ListAddValueList(builder, pValueList)
	return UInt64ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *UInt64ListStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsUInt64List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *UInt64ListStruct) unpackFrom(t *UInt64List) {
	n := t.ValueListLength()
	s.ValueList = make([]uint64, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// Int32ListStruct 对应 table Int32List，用于 flatbuffer 编解码
type Int32ListStruct struct {
	ValueList []int32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Int32ListStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		Int32ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependInt32(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	Int32ListStart(builder)
	Int32ListAddValueList(builder, pValueList)
	return Int32ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Int32ListStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsInt32List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Int32ListStruct) unpackFrom(t *Int32List) {
	n := t.ValueListLength()
	s.ValueList = make([]int32, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// Uint32ListStruct 对应 table Uint32List，用于 flatbuffer 编解码
type Uint32ListStruct struct {
	ValueList []uint32
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Uint32ListStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		Uint32ListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependUint32(s.ValueList[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	Uint32ListStart(builder)
	Uint32ListAddValueList(builder, pValueList)
	return Uint32ListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Uint32ListStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsUint32List(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Uint32ListStruct) unpackFrom(t *Uint32List) {
	n := t.ValueListLength()
	s.ValueList = make([]uint32, n)
	for i := 0; i < n; i++ { s.ValueList[i] = t.ValueList(i) }
}

// StringListStruct 对应 table StringList，用于 flatbuffer 编解码
type StringListStruct struct {
	ValueList []string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *StringListStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pValueList := flatbuffers.UOffsetT(0)
	if len(s.ValueList) > 0 {
		offs := make([]flatbuffers.UOffsetT, len(s.ValueList))
		for i, v := range s.ValueList { offs[i] = builder.CreateString(v) }
		StringListStartValueListVector(builder, len(s.ValueList))
		for i := len(s.ValueList) - 1; i >= 0; i-- { builder.PrependUOffsetT(offs[i]) }
		pValueList = builder.EndVector(len(s.ValueList))
	}
	StringListStart(builder)
	StringListAddValueList(builder, pValueList)
	return StringListEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *StringListStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsStringList(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *StringListStruct) unpackFrom(t *StringList) {
	n := t.ValueListLength()
	s.ValueList = make([]string, n)
	for i := 0; i < n; i++ { s.ValueList[i] = string(t.ValueList(i)) }
}

