// Code generated by fbs2struct. DO NOT EDIT.
package fbbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// RawInputArgsStruct 对应 table RawInputArgs，用于 flatbuffer 编解码
type RawInputArgsStruct struct {
	MsgType uint32
	ClientIdList []uint64
	RawData []byte
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *RawInputArgsStruct) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	pClientIdList := flatbuffers.UOffsetT(0)
	if len(s.ClientIdList) > 0 {
		RawInputArgsStartClientIdListVector(builder, len(s.ClientIdList))
		for i := len(s.ClientIdList) - 1; i >= 0; i-- { builder.PrependUint64(s.ClientIdList[i]) }
		pClientIdList = builder.EndVector(len(s.ClientIdList))
	}
	var pRawData flatbuffers.UOffsetT
	if len(s.RawData) > 0 {
		RawInputArgsStartRawDataVector(builder, len(s.RawData))
		for i := len(s.RawData) - 1; i >= 0; i-- { builder.PrependByte(s.RawData[i]) }
		pRawData = builder.EndVector(len(s.RawData))
	}
	RawInputArgsStart(builder)
	RawInputArgsAddMsgType(builder, s.MsgType)
	RawInputArgsAddClientIdList(builder, pClientIdList)
	RawInputArgsAddRawData(builder, pRawData)
	return RawInputArgsEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *RawInputArgsStruct) UnmarshalFlatBuffer(data []byte) error {
	t := GetRootAsRawInputArgs(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *RawInputArgsStruct) unpackFrom(t *RawInputArgs) {
	s.MsgType = t.MsgType()
	n := t.ClientIdListLength()
	s.ClientIdList = make([]uint64, n)
	for i := 0; i < n; i++ { s.ClientIdList[i] = t.ClientIdList(i) }
	s.RawData = t.RawDataBytes()
}

