// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Int64 struct {
	_tab flatbuffers.Table
}

func GetRootAsInt64(buf []byte, offset flatbuffers.UOffsetT) *Int64 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Int64{}
	x.Init(buf, n+offset)
	return x
}

func FinishInt64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInt64(buf []byte, offset flatbuffers.UOffsetT) *Int64 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Int64{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInt64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Int64) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Int64) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Int64) Value() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Int64) MutateValue(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func Int64Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Int64AddValue(builder *flatbuffers.Builder, value int64) {
	builder.PrependInt64Slot(0, value, 0)
}
func Int64End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
