// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StringList struct {
	_tab flatbuffers.Table
}

func GetRootAsStringList(buf []byte, offset flatbuffers.UOffsetT) *StringList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StringList{}
	x.Init(buf, n+offset)
	return x
}

func FinishStringListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStringList(buf []byte, offset flatbuffers.UOffsetT) *StringList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StringList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStringListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StringList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StringList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StringList) ValueList(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *StringList) ValueListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StringListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StringListAddValueList(builder *flatbuffers.Builder, valueList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(valueList), 0)
}
func StringListStartValueListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StringListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
