// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Uint32 struct {
	_tab flatbuffers.Table
}

func GetRootAsUint32(buf []byte, offset flatbuffers.UOffsetT) *Uint32 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Uint32{}
	x.Init(buf, n+offset)
	return x
}

func FinishUint32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUint32(buf []byte, offset flatbuffers.UOffsetT) *Uint32 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Uint32{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUint32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Uint32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Uint32) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Uint32) Value() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Uint32) MutateValue(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func Uint32Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Uint32AddValue(builder *flatbuffers.Builder, value uint32) {
	builder.PrependUint32Slot(0, value, 0)
}
func Uint32End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
