// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Uint32List struct {
	_tab flatbuffers.Table
}

func GetRootAsUint32List(buf []byte, offset flatbuffers.UOffsetT) *Uint32List {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Uint32List{}
	x.Init(buf, n+offset)
	return x
}

func FinishUint32ListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUint32List(buf []byte, offset flatbuffers.UOffsetT) *Uint32List {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Uint32List{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUint32ListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Uint32List) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Uint32List) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Uint32List) ValueList(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Uint32List) ValueListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Uint32List) MutateValueList(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func Uint32ListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Uint32ListAddValueList(builder *flatbuffers.Builder, valueList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(valueList), 0)
}
func Uint32ListStartValueListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func Uint32ListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
