// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbbase

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UInt64List struct {
	_tab flatbuffers.Table
}

func GetRootAsUInt64List(buf []byte, offset flatbuffers.UOffsetT) *UInt64List {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UInt64List{}
	x.Init(buf, n+offset)
	return x
}

func FinishUInt64ListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUInt64List(buf []byte, offset flatbuffers.UOffsetT) *UInt64List {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UInt64List{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUInt64ListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UInt64List) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UInt64List) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UInt64List) ValueList(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *UInt64List) ValueListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *UInt64List) MutateValueList(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func UInt64ListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UInt64ListAddValueList(builder *flatbuffers.Builder, valueList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(valueList), 0)
}
func UInt64ListStartValueListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func UInt64ListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
