namespace fbgate;

table RpcMsgRegister {
  ShardIdx: int;
  NodeId: string;
  NodeType: string;
}

table RpcS2Client {
  ClientId: string;
  Payload: [ubyte];
}

table RpcS2Clients {
  ClientIds: [string];
  Payload: [ubyte];
}

table RpcC2S {
  ClientId: string;
  GateNodeId: string;
  Payload: [ubyte];
}

table RpcClientDisconnect {
  ClientId: string;
  ClientIds: [string];
}

table RpcAllocClient {
  ClientId: string;
}

table RpcClientLoginLogout {
  UserId: long;
  IsLogin: bool;
  ClientId: string;
  NodeType: string;
  NodeId: string;
  GateNodeId: string;
}

table RpcUnregister {
  NodeId: string;
}

