// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: pbgate/gate.proto

package pbgate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 逻辑服注册到网关: 逻辑服->网关->逻辑服
type RpcMsgRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardIdx int32  `protobuf:"varint,1,opt,name=ShardIdx,proto3" json:"ShardIdx,omitempty"`
	NodeId   string `protobuf:"bytes,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	NodeType string `protobuf:"bytes,3,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
}

func (x *RpcMsgRegister) Reset() {
	*x = RpcMsgRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcMsgRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMsgRegister) ProtoMessage() {}

func (x *RpcMsgRegister) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMsgRegister.ProtoReflect.Descriptor instead.
func (*RpcMsgRegister) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{0}
}

func (x *RpcMsgRegister) GetShardIdx() int32 {
	if x != nil {
		return x.ShardIdx
	}
	return 0
}

func (x *RpcMsgRegister) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RpcMsgRegister) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

// 网关转发消息到客户端: 逻辑服->网关->客户端
type RpcS2Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *RpcS2Client) Reset() {
	*x = RpcS2Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcS2Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcS2Client) ProtoMessage() {}

func (x *RpcS2Client) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcS2Client.ProtoReflect.Descriptor instead.
func (*RpcS2Client) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{1}
}

func (x *RpcS2Client) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RpcS2Client) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 网关转发消息到多个客户端: 逻辑服->网关->多个客户端
type RpcS2Clients struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientIds []string `protobuf:"bytes,1,rep,name=ClientIds,proto3" json:"ClientIds,omitempty"`
	Payload   []byte   `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *RpcS2Clients) Reset() {
	*x = RpcS2Clients{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcS2Clients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcS2Clients) ProtoMessage() {}

func (x *RpcS2Clients) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcS2Clients.ProtoReflect.Descriptor instead.
func (*RpcS2Clients) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{2}
}

func (x *RpcS2Clients) GetClientIds() []string {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

func (x *RpcS2Clients) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 网关转发客户端消息到逻辑服: 客户端->网关->逻辑服
type RpcC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId   string `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	GateNodeId string `protobuf:"bytes,2,opt,name=GateNodeId,proto3" json:"GateNodeId,omitempty"`
	Payload    []byte `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *RpcC2S) Reset() {
	*x = RpcC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcC2S) ProtoMessage() {}

func (x *RpcC2S) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcC2S.ProtoReflect.Descriptor instead.
func (*RpcC2S) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{3}
}

func (x *RpcC2S) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RpcC2S) GetGateNodeId() string {
	if x != nil {
		return x.GateNodeId
	}
	return ""
}

func (x *RpcC2S) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 网关 -> 逻辑服：客户端断开事件。
// 逻辑服的视角相当于连接到本逻辑服的某个客户端断开连接。
type RpcClientDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId  string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	ClientIds []string `protobuf:"bytes,2,rep,name=ClientIds,proto3" json:"ClientIds,omitempty"`
}

func (x *RpcClientDisconnect) Reset() {
	*x = RpcClientDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcClientDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcClientDisconnect) ProtoMessage() {}

func (x *RpcClientDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcClientDisconnect.ProtoReflect.Descriptor instead.
func (*RpcClientDisconnect) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{4}
}

func (x *RpcClientDisconnect) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RpcClientDisconnect) GetClientIds() []string {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

// 网关 -> 逻辑服：分配客户端到本逻辑服。
// 逻辑服的视角相当于某个客户端连接到本逻辑服。
type RpcAllocClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
}

func (x *RpcAllocClient) Reset() {
	*x = RpcAllocClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcAllocClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcAllocClient) ProtoMessage() {}

func (x *RpcAllocClient) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcAllocClient.ProtoReflect.Descriptor instead.
func (*RpcAllocClient) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{5}
}

func (x *RpcAllocClient) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// 逻辑服 -> 网关：客户端登入登出事件
type RpcClientLoginLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	IsLogin    bool   `protobuf:"varint,2,opt,name=IsLogin,proto3" json:"IsLogin,omitempty"`
	ClientId   string `protobuf:"bytes,3,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	NodeType   string `protobuf:"bytes,4,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	NodeId     string `protobuf:"bytes,5,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	GateNodeId string `protobuf:"bytes,6,opt,name=GateNodeId,proto3" json:"GateNodeId,omitempty"`
}

func (x *RpcClientLoginLogout) Reset() {
	*x = RpcClientLoginLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcClientLoginLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcClientLoginLogout) ProtoMessage() {}

func (x *RpcClientLoginLogout) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcClientLoginLogout.ProtoReflect.Descriptor instead.
func (*RpcClientLoginLogout) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{6}
}

func (x *RpcClientLoginLogout) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RpcClientLoginLogout) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *RpcClientLoginLogout) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RpcClientLoginLogout) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *RpcClientLoginLogout) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RpcClientLoginLogout) GetGateNodeId() string {
	if x != nil {
		return x.GateNodeId
	}
	return ""
}

// 逻辑服 -> 网关：逻辑服注销事件
type RpcUnregister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
}

func (x *RpcUnregister) Reset() {
	*x = RpcUnregister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbgate_gate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcUnregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcUnregister) ProtoMessage() {}

func (x *RpcUnregister) ProtoReflect() protoreflect.Message {
	mi := &file_pbgate_gate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcUnregister.ProtoReflect.Descriptor instead.
func (*RpcUnregister) Descriptor() ([]byte, []int) {
	return file_pbgate_gate_proto_rawDescGZIP(), []int{7}
}

func (x *RpcUnregister) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_pbgate_gate_proto protoreflect.FileDescriptor

var file_pbgate_gate_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x67, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x67, 0x61, 0x74, 0x65, 0x22, 0x60, 0x0a, 0x0e, 0x52,
	0x70, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x43, 0x0a,
	0x0b, 0x52, 0x70, 0x63, 0x53, 0x32, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x46, 0x0a, 0x0c, 0x52, 0x70, 0x63, 0x53, 0x32, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5e, 0x0a, 0x06, 0x52, 0x70,
	0x63, 0x43, 0x32, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4f, 0x0a, 0x13, 0x52, 0x70,
	0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x52,
	0x70, 0x63, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xb8, 0x01, 0x0a, 0x14, 0x52, 0x70,
	0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x70, 0x63, 0x55, 0x6e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pbgate_gate_proto_rawDescOnce sync.Once
	file_pbgate_gate_proto_rawDescData = file_pbgate_gate_proto_rawDesc
)

func file_pbgate_gate_proto_rawDescGZIP() []byte {
	file_pbgate_gate_proto_rawDescOnce.Do(func() {
		file_pbgate_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbgate_gate_proto_rawDescData)
	})
	return file_pbgate_gate_proto_rawDescData
}

var file_pbgate_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pbgate_gate_proto_goTypes = []interface{}{
	(*RpcMsgRegister)(nil),       // 0: pbgate.RpcMsgRegister
	(*RpcS2Client)(nil),          // 1: pbgate.RpcS2Client
	(*RpcS2Clients)(nil),         // 2: pbgate.RpcS2Clients
	(*RpcC2S)(nil),               // 3: pbgate.RpcC2S
	(*RpcClientDisconnect)(nil),  // 4: pbgate.RpcClientDisconnect
	(*RpcAllocClient)(nil),       // 5: pbgate.RpcAllocClient
	(*RpcClientLoginLogout)(nil), // 6: pbgate.RpcClientLoginLogout
	(*RpcUnregister)(nil),        // 7: pbgate.RpcUnregister
}
var file_pbgate_gate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbgate_gate_proto_init() }
func file_pbgate_gate_proto_init() {
	if File_pbgate_gate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbgate_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcMsgRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbgate_gate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcS2Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbgate_gate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcS2Clients); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbgate_gate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbgate_gate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcClientDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbgate_gate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcAllocClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbgate_gate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcClientLoginLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbgate_gate_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcUnregister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbgate_gate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbgate_gate_proto_goTypes,
		DependencyIndexes: file_pbgate_gate_proto_depIdxs,
		MessageInfos:      file_pbgate_gate_proto_msgTypes,
	}.Build()
	File_pbgate_gate_proto = out.File
	file_pbgate_gate_proto_rawDesc = nil
	file_pbgate_gate_proto_goTypes = nil
	file_pbgate_gate_proto_depIdxs = nil
}
