// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgate

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpcClientDisconnect struct {
	_tab flatbuffers.Table
}

func GetRootAsRpcClientDisconnect(buf []byte, offset flatbuffers.UOffsetT) *RpcClientDisconnect {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpcClientDisconnect{}
	x.Init(buf, n+offset)
	return x
}

func FinishRpcClientDisconnectBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRpcClientDisconnect(buf []byte, offset flatbuffers.UOffsetT) *RpcClientDisconnect {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RpcClientDisconnect{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRpcClientDisconnectBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RpcClientDisconnect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpcClientDisconnect) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpcClientDisconnect) ClientId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RpcClientDisconnect) ClientIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *RpcClientDisconnect) ClientIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RpcClientDisconnectStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RpcClientDisconnectAddClientId(builder *flatbuffers.Builder, clientId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(clientId), 0)
}
func RpcClientDisconnectAddClientIds(builder *flatbuffers.Builder, clientIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(clientIds), 0)
}
func RpcClientDisconnectStartClientIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RpcClientDisconnectEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
