// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgate

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpcAllocClient struct {
	_tab flatbuffers.Table
}

func GetRootAsRpcAllocClient(buf []byte, offset flatbuffers.UOffsetT) *RpcAllocClient {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpcAllocClient{}
	x.Init(buf, n+offset)
	return x
}

func FinishRpcAllocClientBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRpcAllocClient(buf []byte, offset flatbuffers.UOffsetT) *RpcAllocClient {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RpcAllocClient{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRpcAllocClientBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RpcAllocClient) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpcAllocClient) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpcAllocClient) ClientId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RpcAllocClientStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RpcAllocClientAddClientId(builder *flatbuffers.Builder, clientId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(clientId), 0)
}
func RpcAllocClientEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
