// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgate

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpcClientLoginLogout struct {
	_tab flatbuffers.Table
}

func GetRootAsRpcClientLoginLogout(buf []byte, offset flatbuffers.UOffsetT) *RpcClientLoginLogout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpcClientLoginLogout{}
	x.Init(buf, n+offset)
	return x
}

func FinishRpcClientLoginLogoutBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRpcClientLoginLogout(buf []byte, offset flatbuffers.UOffsetT) *RpcClientLoginLogout {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RpcClientLoginLogout{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRpcClientLoginLogoutBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RpcClientLoginLogout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpcClientLoginLogout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpcClientLoginLogout) UserId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RpcClientLoginLogout) MutateUserId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *RpcClientLoginLogout) IsLogin() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RpcClientLoginLogout) MutateIsLogin(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *RpcClientLoginLogout) ClientId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RpcClientLoginLogout) NodeType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RpcClientLoginLogout) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RpcClientLoginLogout) GateNodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RpcClientLoginLogoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func RpcClientLoginLogoutAddUserId(builder *flatbuffers.Builder, userId int64) {
	builder.PrependInt64Slot(0, userId, 0)
}
func RpcClientLoginLogoutAddIsLogin(builder *flatbuffers.Builder, isLogin bool) {
	builder.PrependBoolSlot(1, isLogin, false)
}
func RpcClientLoginLogoutAddClientId(builder *flatbuffers.Builder, clientId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(clientId), 0)
}
func RpcClientLoginLogoutAddNodeType(builder *flatbuffers.Builder, nodeType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(nodeType), 0)
}
func RpcClientLoginLogoutAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(nodeId), 0)
}
func RpcClientLoginLogoutAddGateNodeId(builder *flatbuffers.Builder, gateNodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(gateNodeId), 0)
}
func RpcClientLoginLogoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
