// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgate

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpcMsgRegister struct {
	_tab flatbuffers.Table
}

func GetRootAsRpcMsgRegister(buf []byte, offset flatbuffers.UOffsetT) *RpcMsgRegister {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpcMsgRegister{}
	x.Init(buf, n+offset)
	return x
}

func FinishRpcMsgRegisterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRpcMsgRegister(buf []byte, offset flatbuffers.UOffsetT) *RpcMsgRegister {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RpcMsgRegister{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRpcMsgRegisterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RpcMsgRegister) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpcMsgRegister) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpcMsgRegister) ShardIdx() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RpcMsgRegister) MutateShardIdx(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RpcMsgRegister) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RpcMsgRegister) NodeType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RpcMsgRegisterStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RpcMsgRegisterAddShardIdx(builder *flatbuffers.Builder, shardIdx int32) {
	builder.PrependInt32Slot(0, shardIdx, 0)
}
func RpcMsgRegisterAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nodeId), 0)
}
func RpcMsgRegisterAddNodeType(builder *flatbuffers.Builder, nodeType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(nodeType), 0)
}
func RpcMsgRegisterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
