// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgate

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpcUnregister struct {
	_tab flatbuffers.Table
}

func GetRootAsRpcUnregister(buf []byte, offset flatbuffers.UOffsetT) *RpcUnregister {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpcUnregister{}
	x.Init(buf, n+offset)
	return x
}

func FinishRpcUnregisterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRpcUnregister(buf []byte, offset flatbuffers.UOffsetT) *RpcUnregister {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RpcUnregister{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRpcUnregisterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RpcUnregister) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpcUnregister) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpcUnregister) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RpcUnregisterStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RpcUnregisterAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func RpcUnregisterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
