syntax = "proto3";
package pbcluster;
option go_package = ".;pbcluster";

// member data
message MemberInfo {
	string              NodeID = 1;
	string              NodeType = 2;
	string              Address = 3;
	int64               Weight = 4;
	int64               Status = 5;
	map<string, string> Settings = 6;
}

// member list data
message MemberInfoList {
	repeated MemberInfo List = 1;
}

message DiscoveryRequest {
	string RequesterID = 1;
}



message ClusterPacket {
	int64 BuildTime = 1; 	// 构建时间（毫秒）
	int64 Timeout = 2; 		// 函数请求超时时间(毫秒)
	string SourcePath = 3; 	// 源节点路径
	string TargetPath = 4; 	// 目标节点路径
	string Sid = 7;				// session unique id
	string FuncName = 5;	// 函数名
	bytes ArgBytes = 6;		// 函数参数
}

message ClusterRequest {
	string RequestID = 1;		// 请求id（自动生成）
	string SourceNodeID = 2;	// 源节点id
	ClusterPacket Packet = 3;	// 消息包
}

message ClusterResponse {
	string RequestID = 1;	// 请求id（与请求消息的requestID相同）
	int32 Code = 2;			// 错误码（ClusterErrorCode），0表示成功，其他表示失败
	bytes Data = 3;			// 返回数据
}
