// Code generated by fbs2struct. DO NOT EDIT.
package fbtrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
	fb "github.com/vvisun/kkdg/proto/pbrpc/fbrpc"
)

// Frame 对应 table Frame，用于 flatbuffer 编解码
type Frame struct {
	T uint32
	ID uint64
	DL int64
	M string
	P []byte
	Code int32
	Err string
}

// Pack 实现 flatbuffer.FlatBufferPackable
func (s *Frame) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var oM flatbuffers.UOffsetT
	if s.M != "" { oM = builder.CreateString(s.M) }
	var pP flatbuffers.UOffsetT
	if len(s.P) > 0 {
		fb.FrameStartPVector(builder, len(s.P))
		for i := len(s.P) - 1; i >= 0; i-- { builder.PrependByte(s.P[i]) }
		pP = builder.EndVector(len(s.P))
	}
	var oErr flatbuffers.UOffsetT
	if s.Err != "" { oErr = builder.CreateString(s.Err) }
	fb.FrameStart(builder)
	fb.FrameAddT(builder, s.T)
	fb.FrameAddId(builder, s.ID)
	fb.FrameAddDl(builder, s.DL)
	fb.FrameAddM(builder, oM)
	fb.FrameAddP(builder, pP)
	fb.FrameAddCode(builder, s.Code)
	fb.FrameAddErr(builder, oErr)
	return fb.FrameEnd(builder)
}

// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体
func (s *Frame) UnmarshalFlatBuffer(data []byte) error {
	t := fb.GetRootAsFrame(data, 0)
	s.unpackFrom(t)
	return nil
}

func (s *Frame) unpackFrom(t *fb.Frame) {
	s.T = t.T()
	s.ID = t.Id()
	s.DL = t.Dl()
	s.M = string(t.M())
	s.P = t.PBytes()
	s.Code = t.Code()
	s.Err = string(t.Err())
}

