// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: test1.proto

package ptoexam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AaaaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data  string `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Extra string `protobuf:"bytes,3,opt,name=Extra,proto3" json:"Extra,omitempty"`
}

func (x *AaaaReq) Reset() {
	*x = AaaaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AaaaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AaaaReq) ProtoMessage() {}

func (x *AaaaReq) ProtoReflect() protoreflect.Message {
	mi := &file_test1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AaaaReq.ProtoReflect.Descriptor instead.
func (*AaaaReq) Descriptor() ([]byte, []int) {
	return file_test1_proto_rawDescGZIP(), []int{0}
}

func (x *AaaaReq) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AaaaReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AaaaReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type AaaaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Damage int32  `protobuf:"varint,3,opt,name=Damage,proto3" json:"Damage,omitempty"`
}

func (x *AaaaResp) Reset() {
	*x = AaaaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AaaaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AaaaResp) ProtoMessage() {}

func (x *AaaaResp) ProtoReflect() protoreflect.Message {
	mi := &file_test1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AaaaResp.ProtoReflect.Descriptor instead.
func (*AaaaResp) Descriptor() ([]byte, []int) {
	return file_test1_proto_rawDescGZIP(), []int{1}
}

func (x *AaaaResp) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AaaaResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AaaaResp) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type BbbbResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Hp int32 `protobuf:"varint,2,opt,name=Hp,proto3" json:"Hp,omitempty"`
}

func (x *BbbbResp) Reset() {
	*x = BbbbResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BbbbResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BbbbResp) ProtoMessage() {}

func (x *BbbbResp) ProtoReflect() protoreflect.Message {
	mi := &file_test1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BbbbResp.ProtoReflect.Descriptor instead.
func (*BbbbResp) Descriptor() ([]byte, []int) {
	return file_test1_proto_rawDescGZIP(), []int{2}
}

func (x *BbbbResp) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BbbbResp) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

var File_test1_proto protoreflect.FileDescriptor

var file_test1_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x74, 0x6f, 0x65, 0x78, 0x61, 0x6d, 0x22, 0x43, 0x0a, 0x07, 0x41, 0x61, 0x61, 0x61, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x22, 0x46, 0x0a, 0x08, 0x41,
	0x61, 0x61, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x44,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x44, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x08, 0x42, 0x62, 0x62, 0x62, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x0e, 0x0a, 0x02, 0x48, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x48, 0x70, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x70, 0x74, 0x6f, 0x65, 0x78, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test1_proto_rawDescOnce sync.Once
	file_test1_proto_rawDescData = file_test1_proto_rawDesc
)

func file_test1_proto_rawDescGZIP() []byte {
	file_test1_proto_rawDescOnce.Do(func() {
		file_test1_proto_rawDescData = protoimpl.X.CompressGZIP(file_test1_proto_rawDescData)
	})
	return file_test1_proto_rawDescData
}

var file_test1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test1_proto_goTypes = []interface{}{
	(*AaaaReq)(nil),  // 0: ptoexam.AaaaReq
	(*AaaaResp)(nil), // 1: ptoexam.AaaaResp
	(*BbbbResp)(nil), // 2: ptoexam.BbbbResp
}
var file_test1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test1_proto_init() }
func file_test1_proto_init() {
	if File_test1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AaaaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AaaaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BbbbResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test1_proto_goTypes,
		DependencyIndexes: file_test1_proto_depIdxs,
		MessageInfos:      file_test1_proto_msgTypes,
	}.Build()
	File_test1_proto = out.File
	file_test1_proto_rawDesc = nil
	file_test1_proto_goTypes = nil
	file_test1_proto_depIdxs = nil
}
