// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClusterRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClusterRequest(buf []byte, offset flatbuffers.UOffsetT) *ClusterRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClusterRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishClusterRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClusterRequest(buf []byte, offset flatbuffers.UOffsetT) *ClusterRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClusterRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClusterRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClusterRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClusterRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClusterRequest) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterRequest) SourceNodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterRequest) Packet(obj *ClusterPacket) *ClusterPacket {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ClusterPacket)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ClusterRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ClusterRequestAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func ClusterRequestAddSourceNodeId(builder *flatbuffers.Builder, sourceNodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sourceNodeId), 0)
}
func ClusterRequestAddPacket(builder *flatbuffers.Builder, packet flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(packet), 0)
}
func ClusterRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
