// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DiscoveryRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDiscoveryRequest(buf []byte, offset flatbuffers.UOffsetT) *DiscoveryRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DiscoveryRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishDiscoveryRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDiscoveryRequest(buf []byte, offset flatbuffers.UOffsetT) *DiscoveryRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DiscoveryRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDiscoveryRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DiscoveryRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DiscoveryRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DiscoveryRequest) RequesterId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DiscoveryRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DiscoveryRequestAddRequesterId(builder *flatbuffers.Builder, requesterId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requesterId), 0)
}
func DiscoveryRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
