// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbcluster

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MemberInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsMemberInfo(buf []byte, offset flatbuffers.UOffsetT) *MemberInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MemberInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishMemberInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMemberInfo(buf []byte, offset flatbuffers.UOffsetT) *MemberInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MemberInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMemberInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MemberInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MemberInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MemberInfo) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MemberInfo) NodeType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MemberInfo) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MemberInfo) RpcAddress() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MemberInfo) Weight() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemberInfo) MutateWeight(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *MemberInfo) Status() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemberInfo) MutateStatus(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func MemberInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func MemberInfoAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func MemberInfoAddNodeType(builder *flatbuffers.Builder, nodeType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nodeType), 0)
}
func MemberInfoAddAddress(builder *flatbuffers.Builder, address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(address), 0)
}
func MemberInfoAddRpcAddress(builder *flatbuffers.Builder, rpcAddress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(rpcAddress), 0)
}
func MemberInfoAddWeight(builder *flatbuffers.Builder, weight int64) {
	builder.PrependInt64Slot(4, weight, 0)
}
func MemberInfoAddStatus(builder *flatbuffers.Builder, status int64) {
	builder.PrependInt64Slot(5, status, 0)
}
func MemberInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
