package stubgen

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
)

// Generate returns formatted Go code implementing gnrpc-style stubs.
func Generate(spec Spec) ([]byte, error) {
	if strings.TrimSpace(spec.Package) == "" {
		return nil, fmt.Errorf("stubgen: empty package")
	}
	if strings.TrimSpace(spec.ServiceName) == "" {
		return nil, fmt.Errorf("stubgen: empty serviceName")
	}
	if len(spec.Methods) == 0 {
		return nil, fmt.Errorf("stubgen: empty methods")
	}

	goSvc := strings.TrimSpace(spec.GoServiceName)
	if goSvc == "" {
		goSvc = deriveGoServiceName(spec.ServiceName)
	}
	if goSvc == "" {
		return nil, fmt.Errorf("stubgen: cannot derive goServiceName")
	}

	// Collect imports and type refs
	im := newImportManager()
	im.require("context")
	im.require("github.com/vvisun/kkdg/kknet/rpc/gnrpc")
	protoAlias := im.require("google.golang.org/protobuf/proto")

	typeRefs := make([]methodTypeRef, 0, len(spec.Methods))
	for _, m := range spec.Methods {
		if strings.TrimSpace(m.Name) == "" {
			return nil, fmt.Errorf("stubgen: method with empty name")
		}
		req, err := parseTypeRef(m.Request)
		if err != nil {
			return nil, fmt.Errorf("stubgen: method %s request: %w", m.Name, err)
		}
		resp, err := parseTypeRef(m.Response)
		if err != nil {
			return nil, fmt.Errorf("stubgen: method %s response: %w", m.Name, err)
		}
		reqAlias := im.require(req.ImportPath)
		respAlias := im.require(resp.ImportPath)
		typeRefs = append(typeRefs, methodTypeRef{
			Method:      m.Name,
			ReqImport:   req.ImportPath,
			ReqAlias:    reqAlias,
			ReqType:     req.TypeName,
			RespImport:  resp.ImportPath,
			RespAlias:   respAlias,
			RespType:    resp.TypeName,
			ServiceName: spec.ServiceName,
			GoService:   goSvc,
		})
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gnrpcstubgen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Service: %s\n", spec.ServiceName)
	fmt.Fprintf(&b, "package %s\n\n", spec.Package)

	// imports
	importLines := im.render()
	if len(importLines) > 0 {
		b.WriteString("import (\n")
		for _, line := range importLines {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString(")\n\n")
	}

	// server interface
	fmt.Fprintf(&b, "type %sServer interface {\n", goSvc)
	for _, m := range typeRefs {
		fmt.Fprintf(&b, "\t%s(ctx context.Context, req *%s.%s) (*%s.%s, error)\n",
			m.Method, m.ReqAlias, m.ReqType, m.RespAlias, m.RespType)
	}
	fmt.Fprintf(&b, "}\n\n")

	// server registration
	fmt.Fprintf(&b, "func Register%[1]sServer(s *gnrpc.Server, srv %[1]sServer) {\n", goSvc)
	fmt.Fprintf(&b, "\tif s == nil || srv == nil {\n\t\treturn\n\t}\n")
	fmt.Fprintf(&b, "\ts.RegisterProtoService(gnrpc.ProtoServiceDesc{\n")
	fmt.Fprintf(&b, "\t\tServiceName: %q,\n", spec.ServiceName)
	fmt.Fprintf(&b, "\t\tMethods: []gnrpc.UnaryProtoMethodDesc{\n")
	for _, m := range typeRefs {
		fmt.Fprintf(&b, "\t\t\t{\n")
		fmt.Fprintf(&b, "\t\t\t\tMethodName: %q,\n", m.Method)
		fmt.Fprintf(&b, "\t\t\t\tNewRequest: func() %s.Message { return &%s.%s{} },\n", protoAlias, m.ReqAlias, m.ReqType)
		fmt.Fprintf(&b, "\t\t\t\tHandler: func(ctx context.Context, req %s.Message) (%s.Message, error) {\n", protoAlias, protoAlias)
		fmt.Fprintf(&b, "\t\t\t\t\tin := req.(*%s.%s)\n", m.ReqAlias, m.ReqType)
		fmt.Fprintf(&b, "\t\t\t\t\treturn srv.%s(ctx, in)\n", m.Method)
		fmt.Fprintf(&b, "\t\t\t\t},\n")
		fmt.Fprintf(&b, "\t\t\t},\n")
	}
	fmt.Fprintf(&b, "\t\t},\n")
	fmt.Fprintf(&b, "\t})\n")
	fmt.Fprintf(&b, "}\n\n")

	// client
	fmt.Fprintf(&b, "type %sClient struct { c *gnrpc.Client }\n\n", goSvc)
	fmt.Fprintf(&b, "func New%[1]sClient(c *gnrpc.Client) *%[1]sClient { return &%[1]sClient{c: c} }\n\n", goSvc)
	for _, m := range typeRefs {
		fmt.Fprintf(&b, "func (c *%sClient) %s(ctx context.Context, req *%s.%s, opts ...gnrpc.CallOption) (*%s.%s, error) {\n",
			goSvc, m.Method, m.ReqAlias, m.ReqType, m.RespAlias, m.RespType)
		fmt.Fprintf(&b, "\tif c == nil || c.c == nil { return nil, gnrpc.ErrClientNotConnected }\n")
		fmt.Fprintf(&b, "\tvar out %s.%s\n", m.RespAlias, m.RespType)
		fmt.Fprintf(&b, "\tif err := c.c.InvokeProtoWithOptions(ctx, gnrpc.FullMethodName(%q, %q), req, &out, opts...); err != nil { return nil, err }\n",
			spec.ServiceName, m.Method)
		fmt.Fprintf(&b, "\treturn &out, nil\n")
		fmt.Fprintf(&b, "}\n\n")
	}

	// ensure proto import if needed
	_ = protoAlias // referenced in generated snippets above

	out, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("stubgen: format: %w", err)
	}
	return out, nil
}

type methodTypeRef struct {
	ServiceName string
	GoService   string
	Method      string

	ReqImport  string
	ReqAlias   string
	ReqType    string
	RespImport string
	RespAlias  string
	RespType   string
}

// ---- type ref parsing ----

// expects "import/path.TypeName"
var typeRefRe = regexp.MustCompile(`^(.+)\.([A-Za-z_][A-Za-z0-9_]*)$`)

type typeRef struct {
	ImportPath string
	TypeName   string
}

func parseTypeRef(s string) (typeRef, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return typeRef{}, fmt.Errorf("empty type ref")
	}
	m := typeRefRe.FindStringSubmatch(s)
	if len(m) != 3 {
		return typeRef{}, fmt.Errorf("invalid type ref %q (want import/path.TypeName)", s)
	}
	return typeRef{ImportPath: m[1], TypeName: m[2]}, nil
}

func deriveGoServiceName(service string) string {
	service = strings.Trim(service, "/")
	if service == "" {
		return ""
	}
	// take last segment after "/" or "."
	last := service
	if i := strings.LastIndex(last, "/"); i >= 0 {
		last = last[i+1:]
	}
	if i := strings.LastIndex(last, "."); i >= 0 {
		last = last[i+1:]
	}
	// keep as-is; caller can override.
	return last
}

// ---- imports ----

type importManager struct {
	// importPath -> alias
	m map[string]string
	// alias -> importPath
	rev map[string]string
}

func newImportManager() *importManager {
	return &importManager{
		m:   make(map[string]string),
		rev: make(map[string]string),
	}
}

func (im *importManager) require(path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	if alias, ok := im.m[path]; ok {
		return alias
	}
	alias := deriveAlias(path)
	// avoid collisions
	base := alias
	for i := 2; ; i++ {
		if _, used := im.rev[alias]; !used {
			break
		}
		alias = fmt.Sprintf("%s%d", base, i)
	}
	im.m[path] = alias
	im.rev[alias] = path
	return alias
}

func (im *importManager) usedProto() bool {
	_, ok := im.m["google.golang.org/protobuf/proto"]
	return ok
}

func (im *importManager) render() []string {
	paths := make([]string, 0, len(im.m))
	for p := range im.m {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	lines := make([]string, 0, len(paths))
	for _, p := range paths {
		alias := im.m[p]
		// if alias matches default package name, omit alias
		def := deriveAlias(p)
		if alias == def {
			lines = append(lines, fmt.Sprintf("%q", p))
		} else {
			lines = append(lines, fmt.Sprintf("%s %q", alias, p))
		}
	}
	return lines
}

func deriveAlias(importPath string) string {
	importPath = strings.TrimRight(importPath, "/")
	if importPath == "" {
		return "pkg"
	}
	seg := importPath
	if i := strings.LastIndex(seg, "/"); i >= 0 {
		seg = seg[i+1:]
	}
	// sanitize
	seg = strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z':
			return r
		case r >= 'A' && r <= 'Z':
			return r
		case r >= '0' && r <= '9':
			return r
		case r == '_':
			return r
		default:
			return '_'
		}
	}, seg)
	if seg == "" {
		return "pkg"
	}
	// cannot start with digit
	if seg[0] >= '0' && seg[0] <= '9' {
		return "pkg_" + seg
	}
	return seg
}

