// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: protomsg/comm_login.proto

package pbmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器负载类型
type ServerLoadType int32

const (
	ServerLoadType_Free    ServerLoadType = 0 //空闲
	ServerLoadType_Crowded ServerLoadType = 1 //拥挤
	ServerLoadType_Busy    ServerLoadType = 2 //繁忙
	ServerLoadType_Full    ServerLoadType = 3 //爆满
	ServerLoadType_Close   ServerLoadType = 4 //关服
)

// Enum value maps for ServerLoadType.
var (
	ServerLoadType_name = map[int32]string{
		0: "Free",
		1: "Crowded",
		2: "Busy",
		3: "Full",
		4: "Close",
	}
	ServerLoadType_value = map[string]int32{
		"Free":    0,
		"Crowded": 1,
		"Busy":    2,
		"Full":    3,
		"Close":   4,
	}
)

func (x ServerLoadType) Enum() *ServerLoadType {
	p := new(ServerLoadType)
	*p = x
	return p
}

func (x ServerLoadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerLoadType) Descriptor() protoreflect.EnumDescriptor {
	return file_protomsg_comm_login_proto_enumTypes[0].Descriptor()
}

func (ServerLoadType) Type() protoreflect.EnumType {
	return &file_protomsg_comm_login_proto_enumTypes[0]
}

func (x ServerLoadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerLoadType.Descriptor instead.
func (ServerLoadType) EnumDescriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{0}
}

// 登出原因
type LogoutType int32

const (
	LogoutType_Normal  LogoutType = 0 //正常退出
	LogoutType_Occupy  LogoutType = 1 //挤占&挤号
	LogoutType_KickOut LogoutType = 2 //被踢出去
)

// Enum value maps for LogoutType.
var (
	LogoutType_name = map[int32]string{
		0: "Normal",
		1: "Occupy",
		2: "KickOut",
	}
	LogoutType_value = map[string]int32{
		"Normal":  0,
		"Occupy":  1,
		"KickOut": 2,
	}
)

func (x LogoutType) Enum() *LogoutType {
	p := new(LogoutType)
	*p = x
	return p
}

func (x LogoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_protomsg_comm_login_proto_enumTypes[1].Descriptor()
}

func (LogoutType) Type() protoreflect.EnumType {
	return &file_protomsg_comm_login_proto_enumTypes[1]
}

func (x LogoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogoutType.Descriptor instead.
func (LogoutType) EnumDescriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{1}
}

// 踢出登录
type MsgNotifyLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason int32 `protobuf:"varint,1,opt,name=Reason,proto3" json:"Reason,omitempty"` //退出原因
}

func (x *MsgNotifyLogout) Reset() {
	*x = MsgNotifyLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgNotifyLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNotifyLogout) ProtoMessage() {}

func (x *MsgNotifyLogout) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNotifyLogout.ProtoReflect.Descriptor instead.
func (*MsgNotifyLogout) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{0}
}

func (x *MsgNotifyLogout) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// 客户端登录网关
type MsgLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Token       string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	ShowAreaId  int32  `protobuf:"varint,3,opt,name=ShowAreaId,proto3" json:"ShowAreaId,omitempty"`
	SessionId   string `protobuf:"bytes,4,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Os          string `protobuf:"bytes,5,opt,name=Os,proto3" json:"Os,omitempty"`                   // 客户端设备类型（可不填）
	ChanneCode  int32  `protobuf:"varint,6,opt,name=ChanneCode,proto3" json:"ChanneCode,omitempty"`  //渠道
	ChannePlat  string `protobuf:"bytes,7,opt,name=ChannePlat,proto3" json:"ChannePlat,omitempty"`   //渠道码(平台id)
	ChannelUUID string `protobuf:"bytes,8,opt,name=ChannelUUID,proto3" json:"ChannelUUID,omitempty"` //玩家渠道openid或UUID
}

func (x *MsgLoginReq) Reset() {
	*x = MsgLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginReq) ProtoMessage() {}

func (x *MsgLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginReq.ProtoReflect.Descriptor instead.
func (*MsgLoginReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{1}
}

func (x *MsgLoginReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MsgLoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgLoginReq) GetShowAreaId() int32 {
	if x != nil {
		return x.ShowAreaId
	}
	return 0
}

func (x *MsgLoginReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MsgLoginReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MsgLoginReq) GetChanneCode() int32 {
	if x != nil {
		return x.ChanneCode
	}
	return 0
}

func (x *MsgLoginReq) GetChannePlat() string {
	if x != nil {
		return x.ChannePlat
	}
	return ""
}

func (x *MsgLoginReq) GetChannelUUID() string {
	if x != nil {
		return x.ChannelUUID
	}
	return ""
}

type MsgLoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        int32     `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` // 0 成功
	UserId     int64     `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	SessionId  string    `protobuf:"bytes,3,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	ServerTime int64     `protobuf:"varint,4,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	UserInfo   *UserInfo `protobuf:"bytes,5,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"` //用户信息
}

func (x *MsgLoginRes) Reset() {
	*x = MsgLoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginRes) ProtoMessage() {}

func (x *MsgLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginRes.ProtoReflect.Descriptor instead.
func (*MsgLoginRes) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{2}
}

func (x *MsgLoginRes) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *MsgLoginRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MsgLoginRes) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MsgLoginRes) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *MsgLoginRes) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// 玩家信息查询
type PlayerInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *PlayerInfoReq) Reset() {
	*x = PlayerInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoReq) ProtoMessage() {}

func (x *PlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoReq.ProtoReflect.Descriptor instead.
func (*PlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInfoReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayerInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOnline bool      `protobuf:"varint,1,opt,name=IsOnline,proto3" json:"IsOnline,omitempty"`
	Data     *UserInfo `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *PlayerInfoResp) Reset() {
	*x = PlayerInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoResp) ProtoMessage() {}

func (x *PlayerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoResp.ProtoReflect.Descriptor instead.
func (*PlayerInfoResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInfoResp) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *PlayerInfoResp) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 在线玩家列表
type OnlinePlayersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlinePlayersReq) Reset() {
	*x = OnlinePlayersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlinePlayersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePlayersReq) ProtoMessage() {}

func (x *OnlinePlayersReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePlayersReq.ProtoReflect.Descriptor instead.
func (*OnlinePlayersReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{5}
}

type OnlinePlayersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataArr []*UserInfo `protobuf:"bytes,1,rep,name=DataArr,proto3" json:"DataArr,omitempty"`
}

func (x *OnlinePlayersResp) Reset() {
	*x = OnlinePlayersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlinePlayersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePlayersResp) ProtoMessage() {}

func (x *OnlinePlayersResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePlayersResp.ProtoReflect.Descriptor instead.
func (*OnlinePlayersResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{6}
}

func (x *OnlinePlayersResp) GetDataArr() []*UserInfo {
	if x != nil {
		return x.DataArr
	}
	return nil
}

// 存取保险柜
type SafeBoxOpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType int32 `protobuf:"varint,1,opt,name=OpType,proto3" json:"OpType,omitempty"` // 1:存 2:取
	Amount int64 `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"` //存取数额
}

func (x *SafeBoxOpReq) Reset() {
	*x = SafeBoxOpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SafeBoxOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeBoxOpReq) ProtoMessage() {}

func (x *SafeBoxOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeBoxOpReq.ProtoReflect.Descriptor instead.
func (*SafeBoxOpReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{7}
}

func (x *SafeBoxOpReq) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *SafeBoxOpReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SafeBoxOpResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType     int32     `protobuf:"varint,1,opt,name=OpType,proto3" json:"OpType,omitempty"`        // 1:存 2:取
	Amount     int64     `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`        //存取数额
	WalletData *UserInfo `protobuf:"bytes,3,opt,name=WalletData,proto3" json:"WalletData,omitempty"` //存取完后的最新钱包信息
}

func (x *SafeBoxOpResp) Reset() {
	*x = SafeBoxOpResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SafeBoxOpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeBoxOpResp) ProtoMessage() {}

func (x *SafeBoxOpResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeBoxOpResp.ProtoReflect.Descriptor instead.
func (*SafeBoxOpResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{8}
}

func (x *SafeBoxOpResp) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *SafeBoxOpResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SafeBoxOpResp) GetWalletData() *UserInfo {
	if x != nil {
		return x.WalletData
	}
	return nil
}

// 切换头像
type ChangeHeadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadId int32 `protobuf:"varint,1,opt,name=HeadId,proto3" json:"HeadId,omitempty"`
}

func (x *ChangeHeadReq) Reset() {
	*x = ChangeHeadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeHeadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeHeadReq) ProtoMessage() {}

func (x *ChangeHeadReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeHeadReq.ProtoReflect.Descriptor instead.
func (*ChangeHeadReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeHeadReq) GetHeadId() int32 {
	if x != nil {
		return x.HeadId
	}
	return 0
}

type ChangeHeadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	HeadId int32 `protobuf:"varint,2,opt,name=HeadId,proto3" json:"HeadId,omitempty"`
}

func (x *ChangeHeadResp) Reset() {
	*x = ChangeHeadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeHeadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeHeadResp) ProtoMessage() {}

func (x *ChangeHeadResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeHeadResp.ProtoReflect.Descriptor instead.
func (*ChangeHeadResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeHeadResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChangeHeadResp) GetHeadId() int32 {
	if x != nil {
		return x.HeadId
	}
	return 0
}

// 切换头像框
type ChangeHeadFrameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadFrame int32 `protobuf:"varint,1,opt,name=HeadFrame,proto3" json:"HeadFrame,omitempty"`
}

func (x *ChangeHeadFrameReq) Reset() {
	*x = ChangeHeadFrameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeHeadFrameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeHeadFrameReq) ProtoMessage() {}

func (x *ChangeHeadFrameReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeHeadFrameReq.ProtoReflect.Descriptor instead.
func (*ChangeHeadFrameReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeHeadFrameReq) GetHeadFrame() int32 {
	if x != nil {
		return x.HeadFrame
	}
	return 0
}

type ChangeHeadFrameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int64 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	HeadFrame int32 `protobuf:"varint,2,opt,name=HeadFrame,proto3" json:"HeadFrame,omitempty"`
}

func (x *ChangeHeadFrameResp) Reset() {
	*x = ChangeHeadFrameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeHeadFrameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeHeadFrameResp) ProtoMessage() {}

func (x *ChangeHeadFrameResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeHeadFrameResp.ProtoReflect.Descriptor instead.
func (*ChangeHeadFrameResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeHeadFrameResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChangeHeadFrameResp) GetHeadFrame() int32 {
	if x != nil {
		return x.HeadFrame
	}
	return 0
}

// 切换皮肤
type ChangeAvatarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarId int32 `protobuf:"varint,1,opt,name=AvatarId,proto3" json:"AvatarId,omitempty"`
}

func (x *ChangeAvatarReq) Reset() {
	*x = ChangeAvatarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeAvatarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAvatarReq) ProtoMessage() {}

func (x *ChangeAvatarReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAvatarReq.ProtoReflect.Descriptor instead.
func (*ChangeAvatarReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeAvatarReq) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

type ChangeAvatarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	AvatarId int32 `protobuf:"varint,2,opt,name=AvatarId,proto3" json:"AvatarId,omitempty"`
}

func (x *ChangeAvatarResp) Reset() {
	*x = ChangeAvatarResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeAvatarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAvatarResp) ProtoMessage() {}

func (x *ChangeAvatarResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAvatarResp.ProtoReflect.Descriptor instead.
func (*ChangeAvatarResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeAvatarResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChangeAvatarResp) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

// 切换昵称
type ChangeNickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nick string `protobuf:"bytes,1,opt,name=Nick,proto3" json:"Nick,omitempty"`
}

func (x *ChangeNickReq) Reset() {
	*x = ChangeNickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeNickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNickReq) ProtoMessage() {}

func (x *ChangeNickReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNickReq.ProtoReflect.Descriptor instead.
func (*ChangeNickReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{15}
}

func (x *ChangeNickReq) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

type ChangeNickResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Nick string `protobuf:"bytes,2,opt,name=Nick,proto3" json:"Nick,omitempty"`
}

func (x *ChangeNickResp) Reset() {
	*x = ChangeNickResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_login_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeNickResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNickResp) ProtoMessage() {}

func (x *ChangeNickResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_login_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNickResp.ProtoReflect.Descriptor instead.
func (*ChangeNickResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_login_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeNickResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChangeNickResp) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

var File_protomsg_comm_login_proto protoreflect.FileDescriptor

var file_protomsg_comm_login_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x5f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x6d,
	0x73, 0x67, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0xeb, 0x01, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x4f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x55, 0x55, 0x49, 0x44, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x55, 0x55, 0x49, 0x44,
	0x22, 0xa2, 0x01, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x6d,
	0x73, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x0e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x6d, 0x73, 0x67,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x12, 0x0a, 0x10, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x22, 0x3e, 0x0a, 0x11, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61,
	0x41, 0x72, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x6d, 0x73,
	0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x44, 0x61, 0x74, 0x61,
	0x41, 0x72, 0x72, 0x22, 0x3e, 0x0a, 0x0c, 0x53, 0x61, 0x66, 0x65, 0x42, 0x6f, 0x78, 0x4f, 0x70,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x70, 0x0a, 0x0d, 0x53, 0x61, 0x66, 0x65, 0x42, 0x6f, 0x78, 0x4f, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x6d, 0x73, 0x67,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x49, 0x64, 0x22, 0x3a,
	0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x12, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x45,
	0x0a, 0x13, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x64, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x48, 0x65, 0x61, 0x64,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4e, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x22, 0x36, 0x0a, 0x0e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x69, 0x63, 0x6b, 0x2a, 0x46, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x61,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x72, 0x65, 0x65, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x72, 0x6f, 0x77, 0x64, 0x65, 0x64, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x42, 0x75, 0x73, 0x79, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x04, 0x2a, 0x31, 0x0a, 0x0a, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x79, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x10, 0x02, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x62, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protomsg_comm_login_proto_rawDescOnce sync.Once
	file_protomsg_comm_login_proto_rawDescData = file_protomsg_comm_login_proto_rawDesc
)

func file_protomsg_comm_login_proto_rawDescGZIP() []byte {
	file_protomsg_comm_login_proto_rawDescOnce.Do(func() {
		file_protomsg_comm_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_protomsg_comm_login_proto_rawDescData)
	})
	return file_protomsg_comm_login_proto_rawDescData
}

var file_protomsg_comm_login_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protomsg_comm_login_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protomsg_comm_login_proto_goTypes = []interface{}{
	(ServerLoadType)(0),         // 0: pbmsg.ServerLoadType
	(LogoutType)(0),             // 1: pbmsg.LogoutType
	(*MsgNotifyLogout)(nil),     // 2: pbmsg.MsgNotifyLogout
	(*MsgLoginReq)(nil),         // 3: pbmsg.MsgLoginReq
	(*MsgLoginRes)(nil),         // 4: pbmsg.MsgLoginRes
	(*PlayerInfoReq)(nil),       // 5: pbmsg.PlayerInfoReq
	(*PlayerInfoResp)(nil),      // 6: pbmsg.PlayerInfoResp
	(*OnlinePlayersReq)(nil),    // 7: pbmsg.OnlinePlayersReq
	(*OnlinePlayersResp)(nil),   // 8: pbmsg.OnlinePlayersResp
	(*SafeBoxOpReq)(nil),        // 9: pbmsg.SafeBoxOpReq
	(*SafeBoxOpResp)(nil),       // 10: pbmsg.SafeBoxOpResp
	(*ChangeHeadReq)(nil),       // 11: pbmsg.ChangeHeadReq
	(*ChangeHeadResp)(nil),      // 12: pbmsg.ChangeHeadResp
	(*ChangeHeadFrameReq)(nil),  // 13: pbmsg.ChangeHeadFrameReq
	(*ChangeHeadFrameResp)(nil), // 14: pbmsg.ChangeHeadFrameResp
	(*ChangeAvatarReq)(nil),     // 15: pbmsg.ChangeAvatarReq
	(*ChangeAvatarResp)(nil),    // 16: pbmsg.ChangeAvatarResp
	(*ChangeNickReq)(nil),       // 17: pbmsg.ChangeNickReq
	(*ChangeNickResp)(nil),      // 18: pbmsg.ChangeNickResp
	(*UserInfo)(nil),            // 19: pbmsg.UserInfo
}
var file_protomsg_comm_login_proto_depIdxs = []int32{
	19, // 0: pbmsg.MsgLoginRes.UserInfo:type_name -> pbmsg.UserInfo
	19, // 1: pbmsg.PlayerInfoResp.Data:type_name -> pbmsg.UserInfo
	19, // 2: pbmsg.OnlinePlayersResp.DataArr:type_name -> pbmsg.UserInfo
	19, // 3: pbmsg.SafeBoxOpResp.WalletData:type_name -> pbmsg.UserInfo
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protomsg_comm_login_proto_init() }
func file_protomsg_comm_login_proto_init() {
	if File_protomsg_comm_login_proto != nil {
		return
	}
	file_protomsg_comm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protomsg_comm_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgNotifyLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlinePlayersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlinePlayersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SafeBoxOpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SafeBoxOpResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeHeadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeHeadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeHeadFrameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeHeadFrameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeAvatarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeAvatarResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeNickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_login_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeNickResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protomsg_comm_login_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protomsg_comm_login_proto_goTypes,
		DependencyIndexes: file_protomsg_comm_login_proto_depIdxs,
		EnumInfos:         file_protomsg_comm_login_proto_enumTypes,
		MessageInfos:      file_protomsg_comm_login_proto_msgTypes,
	}.Build()
	File_protomsg_comm_login_proto = out.File
	file_protomsg_comm_login_proto_rawDesc = nil
	file_protomsg_comm_login_proto_goTypes = nil
	file_protomsg_comm_login_proto_depIdxs = nil
}
