// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: protomsg/comm.proto

package pbmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`        //用户ID
	Nick      string `protobuf:"bytes,2,opt,name=Nick,proto3" json:"Nick,omitempty"`             //昵称
	HeadUrl   string `protobuf:"bytes,3,opt,name=HeadUrl,proto3" json:"HeadUrl,omitempty"`       //头像
	Sex       int32  `protobuf:"varint,4,opt,name=Sex,proto3" json:"Sex,omitempty"`              //性别
	Grade     int32  `protobuf:"varint,5,opt,name=Grade,proto3" json:"Grade,omitempty"`          //等级
	Exp       int64  `protobuf:"varint,6,opt,name=Exp,proto3" json:"Exp,omitempty"`              //经验
	Power     int64  `protobuf:"varint,7,opt,name=Power,proto3" json:"Power,omitempty"`          //战斗力
	Vip       int32  `protobuf:"varint,8,opt,name=Vip,proto3" json:"Vip,omitempty"`              //VIP等级
	Gold      int64  `protobuf:"varint,9,opt,name=Gold,proto3" json:"Gold,omitempty"`            //金币
	Diamond   int64  `protobuf:"varint,10,opt,name=Diamond,proto3" json:"Diamond,omitempty"`     //钻石
	Coin      int64  `protobuf:"varint,11,opt,name=Coin,proto3" json:"Coin,omitempty"`           //铜币
	RoomCard  int64  `protobuf:"varint,12,opt,name=RoomCard,proto3" json:"RoomCard,omitempty"`   //体力
	AvatarId  int32  `protobuf:"varint,13,opt,name=AvatarId,proto3" json:"AvatarId,omitempty"`   //时装
	HeadFrame int32  `protobuf:"varint,14,opt,name=HeadFrame,proto3" json:"HeadFrame,omitempty"` //头像框
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserInfo) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

func (x *UserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfo) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *UserInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UserInfo) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *UserInfo) GetVip() int32 {
	if x != nil {
		return x.Vip
	}
	return 0
}

func (x *UserInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UserInfo) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *UserInfo) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *UserInfo) GetRoomCard() int64 {
	if x != nil {
		return x.RoomCard
	}
	return 0
}

func (x *UserInfo) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *UserInfo) GetHeadFrame() int32 {
	if x != nil {
		return x.HeadFrame
	}
	return 0
}

// 玩家信息
type SimpleUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`       //用户ID
	Nick      string `protobuf:"bytes,2,opt,name=Nick,proto3" json:"Nick,omitempty"`            //昵称
	HeadUrl   string `protobuf:"bytes,3,opt,name=HeadUrl,proto3" json:"HeadUrl,omitempty"`      //头像
	Sex       int32  `protobuf:"varint,4,opt,name=Sex,proto3" json:"Sex,omitempty"`             //性别
	Grade     int32  `protobuf:"varint,5,opt,name=Grade,proto3" json:"Grade,omitempty"`         //等级
	Exp       int64  `protobuf:"varint,6,opt,name=Exp,proto3" json:"Exp,omitempty"`             //经验
	Power     int64  `protobuf:"varint,7,opt,name=Power,proto3" json:"Power,omitempty"`         //战斗力
	Vip       int32  `protobuf:"varint,8,opt,name=Vip,proto3" json:"Vip,omitempty"`             //VIP等级
	HeadFrame int32  `protobuf:"varint,9,opt,name=HeadFrame,proto3" json:"HeadFrame,omitempty"` //头像框
}

func (x *SimpleUserInfo) Reset() {
	*x = SimpleUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUserInfo) ProtoMessage() {}

func (x *SimpleUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUserInfo.ProtoReflect.Descriptor instead.
func (*SimpleUserInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleUserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SimpleUserInfo) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *SimpleUserInfo) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

func (x *SimpleUserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *SimpleUserInfo) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *SimpleUserInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *SimpleUserInfo) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *SimpleUserInfo) GetVip() int32 {
	if x != nil {
		return x.Vip
	}
	return 0
}

func (x *SimpleUserInfo) GetHeadFrame() int32 {
	if x != nil {
		return x.HeadFrame
	}
	return 0
}

// 时间信息
type TimeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	TotalMS   int64 `protobuf:"varint,2,opt,name=TotalMS,proto3" json:"TotalMS,omitempty"`
	RemainMS  int64 `protobuf:"varint,3,opt,name=RemainMS,proto3" json:"RemainMS,omitempty"`
}

func (x *TimeInfo) Reset() {
	*x = TimeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeInfo) ProtoMessage() {}

func (x *TimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeInfo.ProtoReflect.Descriptor instead.
func (*TimeInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{2}
}

func (x *TimeInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeInfo) GetTotalMS() int64 {
	if x != nil {
		return x.TotalMS
	}
	return 0
}

func (x *TimeInfo) GetRemainMS() int64 {
	if x != nil {
		return x.RemainMS
	}
	return 0
}

// 属性信息
type PropInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropId    int64 `protobuf:"varint,1,opt,name=PropId,proto3" json:"PropId,omitempty"`       //属性配置ID
	PropValue int64 `protobuf:"varint,2,opt,name=PropValue,proto3" json:"PropValue,omitempty"` //属性值
	IsPercent int32 `protobuf:"varint,3,opt,name=IsPercent,proto3" json:"IsPercent,omitempty"` //是否百分比 1是 0否
}

func (x *PropInfo) Reset() {
	*x = PropInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropInfo) ProtoMessage() {}

func (x *PropInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropInfo.ProtoReflect.Descriptor instead.
func (*PropInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{3}
}

func (x *PropInfo) GetPropId() int64 {
	if x != nil {
		return x.PropId
	}
	return 0
}

func (x *PropInfo) GetPropValue() int64 {
	if x != nil {
		return x.PropValue
	}
	return 0
}

func (x *PropInfo) GetIsPercent() int32 {
	if x != nil {
		return x.IsPercent
	}
	return 0
}

// 模块信息
type ModInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModId int32 `protobuf:"varint,1,opt,name=ModId,proto3" json:"ModId,omitempty"` //模块ID
	State int32 `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"` //0:未开启  1:已开启  2:已领取
}

func (x *ModInfo) Reset() {
	*x = ModInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModInfo) ProtoMessage() {}

func (x *ModInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModInfo.ProtoReflect.Descriptor instead.
func (*ModInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{4}
}

func (x *ModInfo) GetModId() int32 {
	if x != nil {
		return x.ModId
	}
	return 0
}

func (x *ModInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 物品信息
type ItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid      int64 `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`           //所属玩家
	ItemType int32 `protobuf:"varint,3,opt,name=ItemType,proto3" json:"ItemType,omitempty"` //物品类型
	Count    int64 `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`       //数量
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{5}
}

func (x *ItemInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ItemInfo) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *ItemInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 装备信息
type EquipInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CfgId    int32       `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Grade    int32       `protobuf:"varint,3,opt,name=Grade,proto3" json:"Grade,omitempty"`
	CardId   int64       `protobuf:"varint,4,opt,name=CardId,proto3" json:"CardId,omitempty"`
	PropList []*PropInfo `protobuf:"bytes,5,rep,name=PropList,proto3" json:"PropList,omitempty"`
}

func (x *EquipInfo) Reset() {
	*x = EquipInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipInfo) ProtoMessage() {}

func (x *EquipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipInfo.ProtoReflect.Descriptor instead.
func (*EquipInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{6}
}

func (x *EquipInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipInfo) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *EquipInfo) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *EquipInfo) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *EquipInfo) GetPropList() []*PropInfo {
	if x != nil {
		return x.PropList
	}
	return nil
}

// 卡信息
type CardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid      int64       `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	CardId   int32       `protobuf:"varint,3,opt,name=CardId,proto3" json:"CardId,omitempty"`
	TbType   int32       `protobuf:"varint,4,opt,name=TbType,proto3" json:"TbType,omitempty"`
	Star     int32       `protobuf:"varint,5,opt,name=Star,proto3" json:"Star,omitempty"`
	Quality  int32       `protobuf:"varint,6,opt,name=Quality,proto3" json:"Quality,omitempty"`
	Level    int32       `protobuf:"varint,7,opt,name=Level,proto3" json:"Level,omitempty"`
	Grade    int32       `protobuf:"varint,8,opt,name=Grade,proto3" json:"Grade,omitempty"`
	Lineup   int32       `protobuf:"varint,9,opt,name=Lineup,proto3" json:"Lineup,omitempty"`
	Npos     int32       `protobuf:"varint,10,opt,name=Npos,proto3" json:"Npos,omitempty"`
	PropList []*PropInfo `protobuf:"bytes,11,rep,name=PropList,proto3" json:"PropList,omitempty"`
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{7}
}

func (x *CardInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CardInfo) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CardInfo) GetTbType() int32 {
	if x != nil {
		return x.TbType
	}
	return 0
}

func (x *CardInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *CardInfo) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *CardInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CardInfo) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *CardInfo) GetLineup() int32 {
	if x != nil {
		return x.Lineup
	}
	return 0
}

func (x *CardInfo) GetNpos() int32 {
	if x != nil {
		return x.Npos
	}
	return 0
}

func (x *CardInfo) GetPropList() []*PropInfo {
	if x != nil {
		return x.PropList
	}
	return nil
}

// 养成位信息
type CultivateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid      int64       `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`           //所属Uid
	TbType   int32       `protobuf:"varint,3,opt,name=TbType,proto3" json:"TbType,omitempty"`     //阵类型，和Card表的TbType对应起来
	Npos     int32       `protobuf:"varint,4,opt,name=Npos,proto3" json:"Npos,omitempty"`         //阵位
	Star     int32       `protobuf:"varint,5,opt,name=Star,proto3" json:"Star,omitempty"`         //星级
	Quality  int32       `protobuf:"varint,6,opt,name=Quality,proto3" json:"Quality,omitempty"`   //品级
	Level    int32       `protobuf:"varint,7,opt,name=Level,proto3" json:"Level,omitempty"`       //阶级
	Grade    int32       `protobuf:"varint,8,opt,name=Grade,proto3" json:"Grade,omitempty"`       //等级
	HeroId   int64       `protobuf:"varint,9,opt,name=HeroId,proto3" json:"HeroId,omitempty"`     //上阵Card的Id, 为0时表示该阵位空闲
	PropList []*PropInfo `protobuf:"bytes,10,rep,name=PropList,proto3" json:"PropList,omitempty"` //属性
}

func (x *CultivateInfo) Reset() {
	*x = CultivateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CultivateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CultivateInfo) ProtoMessage() {}

func (x *CultivateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CultivateInfo.ProtoReflect.Descriptor instead.
func (*CultivateInfo) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{8}
}

func (x *CultivateInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CultivateInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CultivateInfo) GetTbType() int32 {
	if x != nil {
		return x.TbType
	}
	return 0
}

func (x *CultivateInfo) GetNpos() int32 {
	if x != nil {
		return x.Npos
	}
	return 0
}

func (x *CultivateInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *CultivateInfo) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *CultivateInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CultivateInfo) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *CultivateInfo) GetHeroId() int64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *CultivateInfo) GetPropList() []*PropInfo {
	if x != nil {
		return x.PropList
	}
	return nil
}

// 任务定义（每日任务 成就任务 活动任务）
type TaskItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                       //任务ID
	State         int32       `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`                 //任务状态
	Progress      int64       `protobuf:"varint,3,opt,name=Progress,proto3" json:"Progress,omitempty"`           //当前进度（次数、时间）
	TaskKind      int32       `protobuf:"varint,4,opt,name=TaskKind,proto3" json:"TaskKind,omitempty"`           //任务分类
	TaskType      int32       `protobuf:"varint,5,opt,name=TaskType,proto3" json:"TaskType,omitempty"`           //配置: 任务类型
	TotalProgress int64       `protobuf:"varint,6,opt,name=TotalProgress,proto3" json:"TotalProgress,omitempty"` //配置: 要求总进度（次数、时间）
	StartTime     int64       `protobuf:"varint,7,opt,name=StartTime,proto3" json:"StartTime,omitempty"`         //配置: 任务的发起时间
	EndTime       int64       `protobuf:"varint,8,opt,name=EndTime,proto3" json:"EndTime,omitempty"`             //配置: 任务的截止时间
	TaskName      string      `protobuf:"bytes,9,opt,name=TaskName,proto3" json:"TaskName,omitempty"`            //配置: 任务名
	StartCond     string      `protobuf:"bytes,10,opt,name=StartCond,proto3" json:"StartCond,omitempty"`         //配置: 开启条件
	Rewards       []*ItemInfo `protobuf:"bytes,11,rep,name=Rewards,proto3" json:"Rewards,omitempty"`             //配置: 成功奖励
}

func (x *TaskItem) Reset() {
	*x = TaskItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskItem) ProtoMessage() {}

func (x *TaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskItem.ProtoReflect.Descriptor instead.
func (*TaskItem) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{9}
}

func (x *TaskItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskItem) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *TaskItem) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskItem) GetTaskKind() int32 {
	if x != nil {
		return x.TaskKind
	}
	return 0
}

func (x *TaskItem) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *TaskItem) GetTotalProgress() int64 {
	if x != nil {
		return x.TotalProgress
	}
	return 0
}

func (x *TaskItem) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskItem) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskItem) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskItem) GetStartCond() string {
	if x != nil {
		return x.StartCond
	}
	return ""
}

func (x *TaskItem) GetRewards() []*ItemInfo {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// 失败反馈
type ErrorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32  `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"` //错误码
	ErrorStr  string `protobuf:"bytes,2,opt,name=ErrorStr,proto3" json:"ErrorStr,omitempty"`    //错误提示
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorResp) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorResp) GetErrorStr() string {
	if x != nil {
		return x.ErrorStr
	}
	return ""
}

// 物品推送
type ItemInfoPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ItemInfo `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *ItemInfoPush) Reset() {
	*x = ItemInfoPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInfoPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfoPush) ProtoMessage() {}

func (x *ItemInfoPush) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfoPush.ProtoReflect.Descriptor instead.
func (*ItemInfoPush) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{11}
}

func (x *ItemInfoPush) GetData() *ItemInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 每日零点推送
type DailyZeroPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *DailyZeroPush) Reset() {
	*x = DailyZeroPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyZeroPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyZeroPush) ProtoMessage() {}

func (x *DailyZeroPush) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyZeroPush.ProtoReflect.Descriptor instead.
func (*DailyZeroPush) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{12}
}

func (x *DailyZeroPush) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 模块列表
type ModListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModListReq) Reset() {
	*x = ModListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModListReq) ProtoMessage() {}

func (x *ModListReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModListReq.ProtoReflect.Descriptor instead.
func (*ModListReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{13}
}

type ModListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModList []*ModInfo `protobuf:"bytes,1,rep,name=ModList,proto3" json:"ModList,omitempty"`
}

func (x *ModListResp) Reset() {
	*x = ModListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModListResp) ProtoMessage() {}

func (x *ModListResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModListResp.ProtoReflect.Descriptor instead.
func (*ModListResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{14}
}

func (x *ModListResp) GetModList() []*ModInfo {
	if x != nil {
		return x.ModList
	}
	return nil
}

// 模块开放奖励
type MokOpenRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModId int32 `protobuf:"varint,1,opt,name=ModId,proto3" json:"ModId,omitempty"`
}

func (x *MokOpenRewardReq) Reset() {
	*x = MokOpenRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MokOpenRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MokOpenRewardReq) ProtoMessage() {}

func (x *MokOpenRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MokOpenRewardReq.ProtoReflect.Descriptor instead.
func (*MokOpenRewardReq) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{15}
}

func (x *MokOpenRewardReq) GetModId() int32 {
	if x != nil {
		return x.ModId
	}
	return 0
}

type MokOpenRewardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModId   int32       `protobuf:"varint,1,opt,name=ModId,proto3" json:"ModId,omitempty"`
	Rewards []*ItemInfo `protobuf:"bytes,2,rep,name=Rewards,proto3" json:"Rewards,omitempty"`
}

func (x *MokOpenRewardResp) Reset() {
	*x = MokOpenRewardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_comm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MokOpenRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MokOpenRewardResp) ProtoMessage() {}

func (x *MokOpenRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_comm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MokOpenRewardResp.ProtoReflect.Descriptor instead.
func (*MokOpenRewardResp) Descriptor() ([]byte, []int) {
	return file_protomsg_comm_proto_rawDescGZIP(), []int{16}
}

func (x *MokOpenRewardResp) GetModId() int32 {
	if x != nil {
		return x.ModId
	}
	return 0
}

func (x *MokOpenRewardResp) GetRewards() []*ItemInfo {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_protomsg_comm_proto protoreflect.FileDescriptor

var file_protomsg_comm_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x6d, 0x73, 0x67, 0x22, 0xca, 0x02, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65,
	0x78, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x45, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x56, 0x69, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x56, 0x69,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43,
	0x6f, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x0e, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64,
	0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x55,
	0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x53, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x45, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x69, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x56, 0x69, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x48, 0x65, 0x61, 0x64, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x4d, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x4d, 0x53, 0x22, 0x5e, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x50, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x22, 0x35, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x4d, 0x6f, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x6f,
	0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5e, 0x0a, 0x08, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x09, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x08, 0x50,
	0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x8f, 0x02, 0x0a, 0x08, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x54, 0x62, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x54, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x51,
	0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x51, 0x75,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x70, 0x6f,
	0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x70, 0x6f, 0x73, 0x12, 0x2b, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xfc, 0x01, 0x0a, 0x0d, 0x43,
	0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x62, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x54, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x70, 0x6f, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x70, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74,
	0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xc7, 0x02, 0x0a, 0x08, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b,
	0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x6d, 0x73,
	0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x22, 0x45, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x22, 0x33, 0x0a, 0x0c, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x12, 0x23, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x6d, 0x73, 0x67,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x2d, 0x0a, 0x0d, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x5a, 0x65, 0x72, 0x6f, 0x50, 0x75, 0x73, 0x68,
	0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x0c,
	0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x37, 0x0a, 0x0b,
	0x4d, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x07, 0x4d,
	0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x4d, 0x6f,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x10, 0x4d, 0x6f, 0x6b, 0x4f, 0x70, 0x65, 0x6e,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x64,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x6f, 0x64, 0x49, 0x64, 0x22,
	0x54, 0x0a, 0x11, 0x4d, 0x6f, 0x6b, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x6d, 0x73, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x62, 0x6d, 0x73, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protomsg_comm_proto_rawDescOnce sync.Once
	file_protomsg_comm_proto_rawDescData = file_protomsg_comm_proto_rawDesc
)

func file_protomsg_comm_proto_rawDescGZIP() []byte {
	file_protomsg_comm_proto_rawDescOnce.Do(func() {
		file_protomsg_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_protomsg_comm_proto_rawDescData)
	})
	return file_protomsg_comm_proto_rawDescData
}

var file_protomsg_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protomsg_comm_proto_goTypes = []interface{}{
	(*UserInfo)(nil),          // 0: pbmsg.UserInfo
	(*SimpleUserInfo)(nil),    // 1: pbmsg.SimpleUserInfo
	(*TimeInfo)(nil),          // 2: pbmsg.TimeInfo
	(*PropInfo)(nil),          // 3: pbmsg.PropInfo
	(*ModInfo)(nil),           // 4: pbmsg.ModInfo
	(*ItemInfo)(nil),          // 5: pbmsg.ItemInfo
	(*EquipInfo)(nil),         // 6: pbmsg.EquipInfo
	(*CardInfo)(nil),          // 7: pbmsg.CardInfo
	(*CultivateInfo)(nil),     // 8: pbmsg.CultivateInfo
	(*TaskItem)(nil),          // 9: pbmsg.TaskItem
	(*ErrorResp)(nil),         // 10: pbmsg.ErrorResp
	(*ItemInfoPush)(nil),      // 11: pbmsg.ItemInfoPush
	(*DailyZeroPush)(nil),     // 12: pbmsg.DailyZeroPush
	(*ModListReq)(nil),        // 13: pbmsg.ModListReq
	(*ModListResp)(nil),       // 14: pbmsg.ModListResp
	(*MokOpenRewardReq)(nil),  // 15: pbmsg.MokOpenRewardReq
	(*MokOpenRewardResp)(nil), // 16: pbmsg.MokOpenRewardResp
}
var file_protomsg_comm_proto_depIdxs = []int32{
	3, // 0: pbmsg.EquipInfo.PropList:type_name -> pbmsg.PropInfo
	3, // 1: pbmsg.CardInfo.PropList:type_name -> pbmsg.PropInfo
	3, // 2: pbmsg.CultivateInfo.PropList:type_name -> pbmsg.PropInfo
	5, // 3: pbmsg.TaskItem.Rewards:type_name -> pbmsg.ItemInfo
	5, // 4: pbmsg.ItemInfoPush.Data:type_name -> pbmsg.ItemInfo
	4, // 5: pbmsg.ModListResp.ModList:type_name -> pbmsg.ModInfo
	5, // 6: pbmsg.MokOpenRewardResp.Rewards:type_name -> pbmsg.ItemInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protomsg_comm_proto_init() }
func file_protomsg_comm_proto_init() {
	if File_protomsg_comm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protomsg_comm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CultivateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemInfoPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyZeroPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MokOpenRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_comm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MokOpenRewardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protomsg_comm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protomsg_comm_proto_goTypes,
		DependencyIndexes: file_protomsg_comm_proto_depIdxs,
		MessageInfos:      file_protomsg_comm_proto_msgTypes,
	}.Build()
	File_protomsg_comm_proto = out.File
	file_protomsg_comm_proto_rawDesc = nil
	file_protomsg_comm_proto_goTypes = nil
	file_protomsg_comm_proto_depIdxs = nil
}
