syntax = "proto3";
package pbmsg;
option go_package = ".;pbmsg";

import "protomsg/comm.proto";



//服务器负载类型
enum ServerLoadType {
    Free            = 0; //空闲
    Crowded         = 1; //拥挤
    Busy            = 2; //繁忙
    Full            = 3; //爆满
    Close           = 4; //关服
}

// 登出原因
enum LogoutType {
    Normal          = 0;  //正常退出
    Occupy          = 1;  //挤占&挤号
    KickOut         = 2;  //被踢出去
}

// 踢出登录
message MsgNotifyLogout {
    int32 Reason    = 1;  //退出原因
}

// 客户端登录网关
message LoginReq {
    int64 UserId = 1;
    string Token  = 2;
    int32 ShowAreaId  = 3;
    string SessionId = 4;
    string Os = 5; 				// 客户端设备类型（可不填）
	int32 ChanneCode = 6;		//渠道
	string ChannePlat = 7;		//渠道码(平台id)
	string ChannelUUID = 8;		//玩家渠道openid或UUID
}
message LoginRes {
    int32 Ret = 1;  // 0 成功
    int64 UserId = 2;
    string SessionId = 3;
    int64 ServerTime = 4;
    UserInfo UserInfo = 5;  //用户信息
}
