package fbs2struct

import (
	"fmt"
	"io"
	"strings"

	"github.com/vvisun/kkdg/tools/fbspb"
)

// GenOptions 生成选项
type GenOptions struct {
	Package string // Go 包名，默认取 schema namespace
}

// Generate 根据 fbs Schema 生成 Go struct 代码
func Generate(sc *fbspb.Schema, w io.Writer, opts GenOptions) error {
	pkg := opts.Package
	if pkg == "" {
		pkg = sc.Package
	}
	if pkg == "" {
		pkg = "main"
	}

	_, err := fmt.Fprintf(w, "// Code generated by fbs2struct. DO NOT EDIT.\npackage %s\n\n", pkg)
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, "import (\n\tflatbuffers \"github.com/google/flatbuffers/go\"\n)\n\n")
	if err != nil {
		return err
	}

	for _, m := range sc.Messages {
		if m.IsStruct {
			continue
		}
		if err := genTableStruct(w, sc, &m); err != nil {
			return err
		}
	}
	return nil
}

func genTableStruct(w io.Writer, sc *fbspb.Schema, m *fbspb.Message) error {
	structName := m.Name + "Struct"
	tableName := m.Name

	_, err := fmt.Fprintf(w, "// %s 对应 table %s，用于 flatbuffer 编解码\n", structName, tableName)
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(w, "type %s struct {\n", structName)
	if err != nil {
		return err
	}
	for _, f := range m.Fields {
		fieldName := toGoFieldName(f.Name)
		goType := fbsFieldToGoType(f)
		_, err = fmt.Fprintf(w, "\t%s %s\n", fieldName, goType)
		if err != nil {
			return err
		}
	}
	_, err = io.WriteString(w, "}\n\n")
	if err != nil {
		return err
	}

	if err := genPackMethod(w, m, structName, tableName); err != nil {
		return err
	}
	if err := genUnmarshalMethod(w, m, structName, tableName); err != nil {
		return err
	}
	return nil
}

func fbsFieldToGoType(f fbspb.Field) string {
	if f.Repeated {
		if f.Type == "ubyte" || f.Type == "byte" {
			return "[]byte"
		}
		if t, ok := fbsToGoType[f.Type]; ok && t != "[]byte" {
			return "[]" + t
		}
		return "[]*" + f.Type + "Struct"
	}
	if f.Type == "bytes" {
		return "[]byte"
	}
	if t, ok := fbsToGoType[f.Type]; ok {
		return t
	}
	return "*" + f.Type + "Struct"
}

func toGoFieldName(name string) string {
	if name == "" {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func toFlatcFieldName(name string) string {
	if name == "" {
		return name
	}
	if len(name) == 1 {
		return strings.ToUpper(name)
	}
	// flatc: 全大写缩写如 ID->Id, DL->Dl
	if strings.ToUpper(name) == name {
		return strings.ToUpper(name[:1]) + strings.ToLower(name[1:])
	}
	first := name[:1]
	if first >= "a" && first <= "z" {
		return strings.ToUpper(first) + name[1:]
	}
	return name
}

func genPackMethod(w io.Writer, m *fbspb.Message, structName, tableName string) error {
	_, err := fmt.Fprintf(w, "// Pack 实现 flatbuffer.FlatBufferPackable\n")
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(w, "func (s *%s) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {\n", structName)
	if err != nil {
		return err
	}

	// 1. 预先创建 string/vector offset
	for _, f := range m.Fields {
		fieldName := toGoFieldName(f.Name)
		fbName := toFlatcFieldName(f.Name)
		isBytesVec := (f.Repeated && (f.Type == "ubyte" || f.Type == "byte")) || f.Type == "bytes"
		if isBytesVec {
			_, err = fmt.Fprintf(w, "\tvar p%s flatbuffers.UOffsetT\n", fbName)
			if err != nil {
				return err
			}
			_, err = fmt.Fprintf(w, "\tif len(s.%s) > 0 {\n", fieldName)
			if err != nil {
				return err
			}
			_, err = fmt.Fprintf(w, "\t\t%sStart%sVector(builder, len(s.%s))\n", tableName, fbName, fieldName)
			if err != nil {
				return err
			}
			_, err = fmt.Fprintf(w, "\t\tfor i := len(s.%s) - 1; i >= 0; i-- { builder.PrependByte(s.%s[i]) }\n", fieldName, fieldName)
			if err != nil {
				return err
			}
			_, err = fmt.Fprintf(w, "\t\tp%s = builder.EndVector(len(s.%s))\n\t}\n", fbName, fieldName)
			if err != nil {
				return err
			}
		} else if !f.Repeated && (f.Type == "string" || f.Type == "ubyte" || f.Type == "byte") {
			var createFn string
			if f.Type == "string" {
				createFn = "CreateString"
			} else {
				createFn = "CreateByteString"
			}
			_, err = fmt.Fprintf(w, "\tvar o%s flatbuffers.UOffsetT\n", fbName)
			if err != nil {
				return err
			}
			if f.Type == "string" {
				_, err = fmt.Fprintf(w, "\tif s.%s != \"\" { o%s = builder.%s(s.%s) }\n", fieldName, fbName, createFn, fieldName)
			} else {
				_, err = fmt.Fprintf(w, "\tif len(s.%s) > 0 { o%s = builder.%s(s.%s) }\n", fieldName, fbName, createFn, fieldName)
			}
			if err != nil {
				return err
			}
		} else if f.Repeated && fbsToGoType[f.Type] != "" {
			_, err = fmt.Fprintf(w, "\tp%s := flatbuffers.UOffsetT(0)\n", fbName)
			if err != nil {
				return err
			}
			prepend := getPrependFunc(f.Type)
			_, err = fmt.Fprintf(w, "\tif len(s.%s) > 0 {\n\t\t%sStart%sVector(builder, len(s.%s))\n", fieldName, tableName, fbName, fieldName)
			if err != nil {
				return err
			}
			_, err = fmt.Fprintf(w, "\t\tfor i := len(s.%s) - 1; i >= 0; i-- { builder.%s(s.%s[i]) }\n", fieldName, prepend, fieldName)
			if err != nil {
				return err
			}
			_, err = fmt.Fprintf(w, "\t\tp%s = builder.EndVector(len(s.%s))\n\t}\n", fbName, fieldName)
			if err != nil {
				return err
			}
		}
	}

	// 2. Start + Add + End
	_, err = fmt.Fprintf(w, "\t%sStart(builder)\n", tableName)
	if err != nil {
		return err
	}
	for _, f := range m.Fields {
		fieldName := toGoFieldName(f.Name)
		fbName := toFlatcFieldName(f.Name)
		isBytesVec := (f.Repeated && (f.Type == "ubyte" || f.Type == "byte")) || f.Type == "bytes"
		if isBytesVec {
			_, err = fmt.Fprintf(w, "\t%sAdd%s(builder, p%s)\n", tableName, fbName, fbName)
		} else if !f.Repeated && (f.Type == "string" || f.Type == "ubyte" || f.Type == "byte") {
			_, err = fmt.Fprintf(w, "\t%sAdd%s(builder, o%s)\n", tableName, fbName, fbName)
		} else if f.Repeated && fbsToGoType[f.Type] != "" {
			_, err = fmt.Fprintf(w, "\t%sAdd%s(builder, p%s)\n", tableName, fbName, fbName)
		} else if _, ok := fbsToGoType[f.Type]; ok {
			_, err = fmt.Fprintf(w, "\t%sAdd%s(builder, s.%s)\n", tableName, fbName, fieldName)
		} else {
			_, err = fmt.Fprintf(w, "\t// TODO: %s %s\n", f.Type, fieldName)
		}
		if err != nil {
			return err
		}
	}
	_, err = fmt.Fprintf(w, "\treturn %sEnd(builder)\n}\n\n", tableName)
	return err
}

func genUnmarshalMethod(w io.Writer, m *fbspb.Message, structName, tableName string) error {
	getRoot := "GetRootAs" + tableName
	_, err := fmt.Fprintf(w, "// UnmarshalFlatBuffer 实现 flatbuffer.FlatBufferUnmarshaler，从 bytes 填充结构体\n")
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(w, "func (s *%s) UnmarshalFlatBuffer(data []byte) error {\n\tt := %s(data, 0)\n\ts.unpackFrom(t)\n\treturn nil\n}\n\n", structName, getRoot)
	if err != nil {
		return err
	}

	// unpackFrom 从 table 填充到 struct
	_, err = fmt.Fprintf(w, "func (s *%s) unpackFrom(t *%s) {\n", structName, tableName)
	if err != nil {
		return err
	}
	for _, f := range m.Fields {
		fieldName := toGoFieldName(f.Name)
		getter := toGetterName(f.Name)
		bytesSuffix := ""
		if (f.Repeated && (f.Type == "ubyte" || f.Type == "byte")) || f.Type == "bytes" {
			bytesSuffix = "Bytes" // P -> PBytes(), Data -> DataBytes()
		}
		if f.Repeated {
			if f.Type == "ubyte" || f.Type == "byte" {
				_, err = fmt.Fprintf(w, "\ts.%s = t.%s%s()\n", fieldName, getter, bytesSuffix)
			} else if fbsToGoType[f.Type] != "" {
				_, err = fmt.Fprintf(w, "\tn := t.%sLength()\n\t\ts.%s = make([]%s, n)\n\t\tfor i := 0; i < n; i++ { s.%s[i] = t.%s(i) }\n", getter, fieldName, fbsToGoType[f.Type], fieldName, getter)
			} else {
				_, err = fmt.Fprintf(w, "\t// TODO: vector %s\n", f.Type)
			}
		} else {
			switch f.Type {
			case "string":
				_, err = fmt.Fprintf(w, "\ts.%s = string(t.%s())\n", fieldName, getter)
			case "ubyte", "byte", "bytes":
				_, err = fmt.Fprintf(w, "\ts.%s = t.%s%s()\n", fieldName, getter, bytesSuffix)
			default:
				if _, ok := fbsToGoType[f.Type]; ok {
					_, err = fmt.Fprintf(w, "\ts.%s = t.%s()\n", fieldName, getter)
				} else {
					_, err = fmt.Fprintf(w, "\t// TODO: %s\n", f.Type)
				}
			}
		}
		if err != nil {
			return err
		}
	}
	_, err = io.WriteString(w, "}\n\n")
	return err
}

func toGetterName(name string) string {
	return toFlatcFieldName(name)
}

func getPrependFunc(fbsType string) string {
	switch fbsType {
	case "int8", "byte":
		return "PrependByte"
	case "ubyte":
		return "PrependUint8"
	case "int16", "short":
		return "PrependInt16"
	case "uint16", "ushort":
		return "PrependUint16"
	case "int32", "int":
		return "PrependInt32"
	case "uint32", "uint":
		return "PrependUint32"
	case "int64", "long":
		return "PrependInt64"
	case "uint64", "ulong":
		return "PrependUint64"
	case "float32", "float":
		return "PrependFloat32"
	case "float64", "double":
		return "PrependFloat64"
	case "bool":
		return "PrependBool"
	default:
		return "PrependInt32"
	}
}
