// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: pbrpc/rpc.proto

package pbrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T    uint32 `protobuf:"varint,1,opt,name=T,proto3" json:"T,omitempty"`       // FrameType
	ID   uint64 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`     // request id. 0 means no response required
	DL   int64  `protobuf:"varint,3,opt,name=DL,proto3" json:"DL,omitempty"`     // deadline unix ms (0 means no deadline)
	M    string `protobuf:"bytes,4,opt,name=M,proto3" json:"M,omitempty"`        // method（远程方法名）
	P    []byte `protobuf:"bytes,5,opt,name=P,proto3" json:"P,omitempty"`        // payload（远程方法参数）
	Code int32  `protobuf:"varint,6,opt,name=Code,proto3" json:"Code,omitempty"` // status code (0 ok) 错误码
	Err  string `protobuf:"bytes,7,opt,name=Err,proto3" json:"Err,omitempty"`    // error message 错误信息
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbrpc_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pbrpc_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pbrpc_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetT() uint32 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *Frame) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Frame) GetDL() int64 {
	if x != nil {
		return x.DL
	}
	return 0
}

func (x *Frame) GetM() string {
	if x != nil {
		return x.M
	}
	return ""
}

func (x *Frame) GetP() []byte {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *Frame) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Frame) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_pbrpc_rpc_proto protoreflect.FileDescriptor

var file_pbrpc_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x62, 0x72, 0x70, 0x63, 0x22, 0x77, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x54, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x0e, 0x0a, 0x02, 0x44, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x44, 0x4c, 0x12,
	0x0c, 0x0a, 0x01, 0x4d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x4d, 0x12, 0x0c, 0x0a,
	0x01, 0x50, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72,
	0x72, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x62, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbrpc_rpc_proto_rawDescOnce sync.Once
	file_pbrpc_rpc_proto_rawDescData = file_pbrpc_rpc_proto_rawDesc
)

func file_pbrpc_rpc_proto_rawDescGZIP() []byte {
	file_pbrpc_rpc_proto_rawDescOnce.Do(func() {
		file_pbrpc_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbrpc_rpc_proto_rawDescData)
	})
	return file_pbrpc_rpc_proto_rawDescData
}

var file_pbrpc_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbrpc_rpc_proto_goTypes = []interface{}{
	(*Frame)(nil), // 0: pbrpc.Frame
}
var file_pbrpc_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbrpc_rpc_proto_init() }
func file_pbrpc_rpc_proto_init() {
	if File_pbrpc_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbrpc_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbrpc_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbrpc_rpc_proto_goTypes,
		DependencyIndexes: file_pbrpc_rpc_proto_depIdxs,
		MessageInfos:      file_pbrpc_rpc_proto_msgTypes,
	}.Build()
	File_pbrpc_rpc_proto = out.File
	file_pbrpc_rpc_proto_rawDesc = nil
	file_pbrpc_rpc_proto_goTypes = nil
	file_pbrpc_rpc_proto_depIdxs = nil
}
